project-oak/silveroak

- cava/timed_experiments/Timed.v
- cava/timed_experiments/_CoqProject
Some experimental proofs using lists as signals over time
> Timed experiments

- cava/Cava/ArrowExamples.v
I think it would be good to add just a few brief comments about what is going on here.
> Add a few comments for the NAND and XOR arrow examples

- cava/Cava/Arrow.v
- cava/Cava/ArrowExamples.v
Simplifies `CoqEval` and adds NetlistLoop
> Arrow Loops

- cava/.gitignore
- cava/Cava/Arrow.v
- cava/ExamplesSV.hs
- cava/Makefile
- cava/loopedNandArrow_tb.sv
Also fix bug in netlist generation for arrow delays.
> Add SystemVerilog compilation for arrow version of looped NAND

- cava/.gitignore
- cava/Cava/Arrow.v
- cava/ExamplesSV.hs
- cava/Makefile
- cava/README.md
- cava/loopedNandArrow_tb.sv
- cava/verilator.vlt
Add Verilator lint checks for auto-generated SystemVerilog files.
> Add verilator lint checks for automatically generated SystemVerilog files

- cava/default.nix
> Add verilator to nix config dependencies

- .ci/build_docker_image.sh
- cloudbuild.yaml
> Automatically rebuild docker image

- cava/Cava/Arrow.v
- cava/Cava/ArrowExamples.v
- cava/Cava/ArrowStream.v
Attempt at making some simple generalised tactics
> Simple mechanized proofs

- cava/Cava/Arrow/ArrowExamples.v
- cava/Cava/BitVector.v
- cava/Cava/Cava.v
- cava/Cava/Examples.v
- cava/Cava/Netlist.v
- cava/Cava2SystemVerilog.hs
- cava/ExamplesSV.hs
- cava/Makefile
- cava/adder4_tb.sv
A request for a checkpoint commit that adds just enough functionality to express a 4-bit adder which can be synthesized from SystemVerilog, and a simple test bench (not assertion checking yet).
> Unsigned 4-bit adder (synthesizable)

- cava-examples/.gitignore
- cava-examples/AdderTree.v
- cava-examples/ExamplesSV.hs
- cava-examples/Makefile
- cava/Cava/BitArithmetic.v
- cava/Cava2HDL.cabal
This is a check-point commit for an adder-tree. It does not seem to work, at least I can't get it to simulate in Coq but netlist generation and FPGA implementation works. Addressing #38
> A first attempt at an adder-tree

- cava/cava/Cava/Arrow/Arrow.v
- cava/cava/Cava/Arrow/Instances/Coq.v
- cava/cava/Cava/Arrow/Instances/Netlist.v
- cava/cava/Cava/Arrow/Instances/Stream.v
- cava/cava/Cava/Extraction.v
- cava/cava/Cava/Monad/Cava.v
- cava/cava/Cava/Monad/UnsignedAdders.v
- cava/cava/Cava/Netlist.v
- cava/cava/Cava2HDL.cabal
- cava/cava/Cava2SystemVerilog.hs
- cava/cava/_CoqProject
- cava/monad-examples/AdderTree.v
- cava/monad-examples/Examples.v
- cava/monad-examples/ExamplesSV.hs
- cava/monad-examples/Extraction.v
- cava/monad-examples/Makefile
- cava/monad-examples/UnsignedAdderExamples.v
- cava/monad-examples/_CoqProject
- cava/monad-examples/testbench/adder8_3input_tb.sv
Also some re-organization to put unsigned adders into a file under `Cava.Monad`.
Addresses #56
> Change unsignedAdder to take explicit sum length

- cava/arrow-examples/.gitignore
- cava/arrow-examples/Makefile
- cava/arrow-examples/testbench/loopedNandArrow_tb.sv
- cava/arrow-examples/testbench/xorArrow_tb.sv
- cava/monad-examples/Makefile
The arrow tests were in the wrong place. Move them to the correct place and re-activate these tests.
> Move arrow test-benches to correct location and activate

- cava/cava/Cava/Monad/Combinators.v
These proofs tell us general facts about the properties of `col` and how it relates to `below` which we can then use for proofs of col-based circuits e.g. a ripple-carry adder.
> Proofs relating the col combinator to the below combinator

- cava/monad-examples/xilinx/Makefile
- cava/monad-examples/xilinx/XilinxAdderExamples.v
- cava/monad-examples/xilinx/XilinxAdderTree.v
Minor cleanup for Xilinx examples.
> Convert compute in Xilinx adder tree example to Example as regression test

- cava/cava/Cava/Monad/Cava.v
- cava/cava/Cava/Netlist.v
- cava/cava/Cava2SystemVerilog.hs
- cava/tests/xilinx/LUTTests.v
- cava/tests/xilinx/Makefile
- cava/tests/xilinx/VivadoTestsSV.hs
```console
clang++ -L/usr/local/opt/sqlite/lib    lut5_and_tb.o verilated.o verilated_vcd_c.o Vlut5_and_tb__ALL.a    -o Vlut5_and_tb -lm -lstdc++ 
obj_dir/Vlut5_and_tb
10: tick = 0, i0 = 0, i1 = 0, i2 = 0, i3 = 0, i4 = 0, o = 0
20: tick = 1, i0 = 1, i1 = 1, i2 = 1, i3 = 1, i4 = 1, o = 1
PASSED
```
> Implement and test LUT5

- cava/cava/Cava/Monad/Cava.v
- cava/cava/Cava/Netlist.v
- cava/cava/Cava2SystemVerilog.hs
- cava/tests/xilinx/LUTTests.v
- cava/tests/xilinx/Makefile
- cava/tests/xilinx/VivadoTestsSV.hs
```console
clang++ -L/usr/local/opt/sqlite/lib    lut6_and_tb.o verilated.o verilated_vcd_c.o Vlut6_and_tb__ALL.a    -o Vlut6_and_tb -lm -lstdc++ 
obj_dir/Vlut6_and_tb
10: tick = 0, i0 = 0, i1 = 0, i2 = 0, i3 = 0, i4 = 0, i5 = 0, o = 0
20: tick = 1, i0 = 1, i1 = 1, i2 = 1, i3 = 1, i4 = 1, i5 = 1, o = 1
PASSED
```
> Implement LUT6 and test

- cava/arrow-examples/Mux2_1.v
- cava/arrow-examples/_CoqProject
Just the definition of a 2 to 1 multiplexor for now until arrow evaluation works.
> Add a 2 to 1 multiplexor arrow example

- cava/cava/Cava/Arrow/Arrow.v
- cava/cava/Cava/Arrow/Instances/Combinational.v
- cava/cava/Cava/Arrow/Instances/Constructive.v
- cava/cava/Cava/Arrow/Instances/Netlist.v
- cava/cava/Cava/Arrow/Kappa/CC.v
- cava/cava/Cava/Arrow/Kappa/Syntax.v
And a few small fixes to structural equivalence related items
> Make bitvec multi-dimensional for Arrows

- cava/arrow-examples/ArrowExamples.v
- cava/arrow-examples/Mux2_1.v
- cava/cava/Cava/Arrow/Arrow.v
- cava/cava/Cava/Arrow/Instances/Combinational.v
- cava/cava/Cava/Arrow/Instances/Constructive.v
- cava/cava/Cava/Arrow/Instances/Netlist.v
- cava/cava/Cava/Arrow/Kappa/CC.v
- cava/cava/Cava/Arrow/Kappa/Syntax.v
- cava/cava/Cava/Extraction.v
- cava/cava/Cava/Monad/Cava.v
- cava/cava/Cava/Netlist.v
- cava/cava/Cava/Types.v
- cava/cava/Cava2HDL.cabal
- cava/cava/Cava2SystemVerilog.hs
- cava/cava/_CoqProject
- cava/monad-examples/AdderTree.v
- cava/monad-examples/FullAdder.v
- cava/monad-examples/Multiplexers.v
- cava/monad-examples/NandGate.v
- cava/monad-examples/UnsignedAdderExamples.v
- cava/monad-examples/xilinx/NandLUT.v
- cava/monad-examples/xilinx/XilinxAdderExamples.v
- cava/monad-examples/xilinx/XilinxAdderTree.v
- Part of the motivation here is to start unifying some of the types that i've duplicated in various arrow places.
- I've rolledback the well-founded recursion fixpoint i demonstrated
- I've added experimental  "<< x , y, .., z >>" tuple notation
> Refactor circuit-representable types out of Netlist.v

- cava/arrow-examples/Aes/Pkg.v
- cava/arrow-examples/Aes/Util.v
- cava/arrow-examples/Aes/_CoqProject
- cava/arrow-examples/Aes/canright.v
- cava/arrow-examples/Aes/canright_masked_noreuse.v
- cava/arrow-examples/Aes/canright_pkg.v
- cava/cava/Cava/Arrow/Arrow.v
- cava/cava/Cava/Arrow/Instances/Constructive.v
- cava/cava/Cava/Arrow/Instances/Prop.v
- cava/cava/Cava/Arrow/Kappa/CC.v
- cava/cava/Cava/Arrow/Kappa/Kappa.v
- cava/cava/Cava/Arrow/Kappa/Syntax.v
- Currently compiles but is untested
> Add AES canright and canright_masked_noreuse sboxes

- cava/cava/Cava/Arrow/Instances/Combinational.v
This weakens the requirement for `wf_combinational` in arrows, and allows opaque proofs of circuits being combinational.
> Make wf_combinational non-informative

- .gitignore
Trying to get cleaner and less distracting output from `git status`.
> Add more enteries to .gitignore

- cava/cava/Cava/Monad/Combinators.v
- cava/cava/Cava/Monad/XilinxAdder.v
- cava/monad-examples/xilinx/XilinxAdderTree.v
This addresses #156, and is also careful to generate evaluable terms.
@satnam6502 let me know if I've missed any de-hacking of examples.
> Update type of vector based colV

- cava/arrow-examples/ArrowAdder.v
- cava/arrow-examples/Mux2_1.v
- cava/arrow-examples/SyntaxExamples.v
- cava/cava/Cava/Arrow/CavaExpression.v
- cava/cava/Cava/Arrow/CavaNotation.v
- cava/cava/Cava2HDL.cabal
- Also fix missing modules from Cava2HDL.cabal
> Rename `kappa_sugared` to `CavaExpr`

- cava/cava/Cava/Arrow/NetlistArrow.v
Previously arrow netlist indexing and slicing would only work for vectors containing bits, this fixes the other cases allowing indexing and slicing on vectors containing any kind.
> Enable indexing and slicing on vectors containing arbitrary arrow kinds

- cava/arrow-examples/Aes/_CoqProject
- cava/arrow-examples/Aes/pkg.v
- cava/arrow-examples/Aes/sbox.v
- cava/arrow-examples/Aes/shift_rows.v
- cava/arrow-examples/Aes/sub_bytes.v
- cava/arrow-examples/Combinators.v
- cava/arrow-examples/_CoqProject
- cava/cava/Cava/Arrow/CavaArrow.v
- cava/cava/Cava/Arrow/CavaExpression.v
- cava/cava/Cava/Arrow/CavaNotation.v
- cava/cava/Cava/Arrow/CombinationalArrow.v
- cava/cava/Cava/Arrow/EvaluationArrow.v
- cava/cava/Cava/Arrow/NetlistArrow.v
- cava/cava/Cava/Arrow/PropArrow.v
- Also simplify arrow split definition
> AES logic: Finish sub_bytes and add shift_rows

- cava/cava/Cava/Signal.v
- cava/cava/Cava2SystemVerilog.hs
- cava/experiments/sv-experiments/indexing.sv
- cava/opentitan/pinmux/Pinmux.v
A version of the pinmux in Cava that works on the actual FPGA board.
Very much a work in progress with several things to address in subsequent PRs.
> Cava generated pinmux working.

- cava/cava/Cava/Netlist.v
- cava/cava/Cava2SystemVerilog.hs
- cava/experiments/sv-experiments/indexing.sv
This adds netlist layer support for an unsigned subtractor.
> Add a synthesizable unsigned subtractor to the netlist layer

- cava/arrow-examples/Aes/naive_unrolled_cipher.v
- cava/arrow-examples/Aes/pkg.v
- cava/arrow-examples/Combinators.v
- cava/arrow-examples/_CoqProject
- cava/cava/Cava/Arrow/CavaNotation.v
- cava/cava/Cava/Arrow/CombinationalArrow.v
- cava/cava/Cava2HDL.cabal
Key expansion not based on the open titan routines
> Naive key expansion

- cava/arrow-examples/Aes/cipher_round.v
- cava/arrow-examples/Aes/naive_unrolled_cipher.v
- cava/arrow-examples/Aes/pkg.v
- cava/arrow-examples/Aes/unrolled_cipher.v
- cava/arrow-examples/Combinators.v
- cava/arrow-examples/_CoqProject
- cava/cava/Cava/BitArithmetic.v
- cava/cava/Cava/VectorUtils.v
- cava/cava/Cava2HDL.cabal
This uses the OpenTitan derived primitives, but is a simple unrolled structure
> Working simple AES-256

- cava/arrow-examples/Aes/sbox.v
- cava/arrow-examples/Aes/sbox_canright.v
- cava/arrow-examples/Aes/shift_rows.v
- cava/cava/Cava/Arrow/ArrowKind.v
- cava/cava/Cava/Arrow/CavaArrow.v
- cava/cava/Cava/Arrow/CombinationalArrow.v
- cava/cava/Cava/Arrow/NetlistArrow.v
https://github.com/project-oak/oak-hardware/compare/main...blaxill:inversion_proofs?expand=1#diff-02298347779c6fa5bad3bbfccd9f4c62#R78-R82
~~these axioms come from the disabled circuit laws class. Perhaps this section shouldnt be included~~
> Misc. items from pair programming sessions

- README.md
> Fix path to monad circuit examples

- investigations/modeling/Makefile
- investigations/modeling/Modeling.v
- investigations/modeling/_CoqProject
A "note" to check in which illustrates an alternative way to attribute sequential circuits by viewing signals as functions from a time index to a value, rather than as a list of values or stream of values. Next step would be to model a circuit with a loop e.g.. a counter.
> Time indexed sequential semantics experiments

- Makefile
- arrow-examples/Makefile
- cava/Makefile
- cloudbuild.yaml
- monad-examples/Makefile
- monad-examples/xilinx/Makefile
- silveroak-opentitan/Makefile
- silveroak-opentitan/pinmux/Makefile
- tests/Makefile
- tests/xilinx/Makefile
- third_party/Makefile
If it works, fixes #248 
I have no idea if this works, but I need to create a PR for it for the build to run.
> Run `make` in parallel mode for presubmit

- cava/Cava/Acorn/AcornCavaClass.v
- cava/Cava/Acorn/AcornCombinators.v
- cava/Cava/Acorn/AcornNetlist.v
- cava/Cava/Acorn/AcornNetlistGeneration.v
- cava/Cava/Acorn/AcornSignal.v
- cava/Cava/Acorn/AcornState.v
- cava/Cava/Acorn/Lib/AcornFullAdder.v
- cava/Cava/Acorn/Lib/AcornUnsignedAdders.v
- cava/Cava/Acorn/Lib/AcornVectors.v
- cava/_CoqProject
- silveroak-opentitan/aes/Acorn/CipherRound.v
- silveroak-opentitan/aes/Acorn/Makefile
- silveroak-opentitan/aes/Acorn/_CoqProject
I still need to flesh things out, but @jadephilipoom please can you take a look at silveroak-opentitan/aes/Acorn/CipherRound.v and let me know if this is the kind of thing you were expecting. Thank you kindly.
Addressing #242
> Acorn top level for AES

- cava/Cava/Arrow/CavaNotation.v
- cava/Cava/Arrow/CircuitArrow.v
- cava/Cava/Arrow/CircuitFunctionalEquivalence.v
- cava/Cava/Arrow/CircuitLowering.v
- cava/Cava/Arrow/CircuitProp.v
- cava/Cava/Arrow/CircuitSemantics.v
- cava/Cava/Arrow/Classes/Arrow.v
- cava/Cava/Arrow/Classes/Category.v
- cava/Cava/Arrow/CombinatorProperties.v
- cava/Cava/Arrow/DeriveSpec.v
- cava/Cava/Arrow/ExprEquiv.v
- cava/Cava/Arrow/ExprLowering.v
- cava/Cava/Arrow/ExprSemantics.v
- cava/Cava/Arrow/ExprSyntax.v
- cava/Cava/Arrow/Primitives.v
- silveroak-opentitan/aes/Arrow/_CoqProject
- silveroak-opentitan/aes/Arrow/pkg.v
- This seems to be a performance degradation somewhat, I am investigating options
> Cleanup primitive structures

- arrow-examples/UnsignedAdder.v
- cava/Cava/Arrow/ArrowExport.v
- cava/Cava/Arrow/ArrowKind.v
- cava/Cava/Arrow/CavaNotation.v
- cava/Cava/Arrow/CircuitArrow.v
- cava/Cava/Arrow/CircuitFunctionalEquivalence.v
- cava/Cava/Arrow/CircuitLowering.v
- cava/Cava/Arrow/CircuitProp.v
- cava/Cava/Arrow/CircuitSemantics.v
- cava/Cava/Arrow/Classes/Arrow.v
- cava/Cava/Arrow/Classes/Category.v
- cava/Cava/Arrow/Classes/Coq.v
- cava/Cava/Arrow/Classes/Kleisli.v
- cava/Cava/Arrow/CombinatorProperties.v
- cava/Cava/Arrow/Combinators.v
- cava/Cava/Arrow/DeriveSpec.v
- cava/Cava/Arrow/ExprEquiv.v
- cava/Cava/Arrow/ExprLowering.v
- cava/Cava/Arrow/ExprSemantics.v
- cava/Cava/Arrow/ExprSyntax.v
- cava/Cava/Arrow/Primitives.v
- cava/Cava/Extraction.v
- silveroak-opentitan/aes/Arrow/NaiveCipherProperties.v
- silveroak-opentitan/aes/Arrow/OpenTitanCipherProperties.v
- silveroak-opentitan/aes/Arrow/_CoqProject
- silveroak-opentitan/aes/Arrow/pkg.v
- silveroak-opentitan/aes/Arrow/sbox_canright.v
- silveroak-opentitan/aes/Arrow/sbox_canright_pkg.v
- silveroak-opentitan/aes/Arrow/unrolled_naive_cipher.v
- Also introduces nicer syntax `fun name x .. y => e` but doesnt yet convert Aes components to use it
> Cleanup primitive structures and delimit modules

- arrow-examples/Fir.v
- cava/Cava/Arrow/CavaNotation.v
- cava/Cava/Arrow/CircuitLowering.v
- cava/Cava/Arrow/Primitives.v
- Add `mult` prim and use it in FIR example
> Update arrow FIR example

- silveroak-opentitan/aes/Acorn/AddRoundKey.v
- silveroak-opentitan/aes/Arrow/aes_test.v
Resolves #356 
I went ahead and took a stab at using the new testing infrastructure for Acorn/Arrow expressions as @blaxill suggested, and it just works! Makes me very happy.
Currently, all the Arrow subroutines except for `add_round_key` and `key_expand` are tested. `add_round_key` not tested because it has no separate definition; it's just an inline xor in `cipher_round`. The `key_expand` routine is not tested because we don't have tests for it -- I could create key expansion tests, but I'm not sure if it's a top priority. @blaxill , thoughts?
The only Acorn subroutine currently tested is `add_round_key`, because it's the only one we currently have -- but hopefully the test can be used to help develop the other routines in #320, #321, and #322.
Each of the tests takes 1-2 seconds. They …
> Acorn and Arrow tests

- cava/Cava/Acorn/SequentialProperties.v
- cava/Cava/ListUtils.v
- tests/SignallingCounter/ListProofs.v
Resolves #376 
Adds proofs for the signalling counter using our shiny new tuple machinery.
> Proofs for signalling counter

- cava/Cava/Acorn/CombinationalMonad.v
> Simplify definitions of indexAtBool and indexConstBool to ease proofs

- silveroak-opentitan/aes/Acorn/MixColumns.v
- silveroak-opentitan/aes/Acorn/Pkg.v
> Add Acorn mix_columns

- status.md
This adds a status-tracking file for our remaining critical phase 1 tasks, so we can see them at a glance. ~Some of the tasks are missing issues; I'll create these and add them shortly.~ [EDIT: done]
> Add status tracking file

- tests/TestMultiply.v
> Remove redudnant tuple destruction in TestMultiply

- cava/Cava/Acorn/CombinationalProperties.v
- cava/Cava/Acorn/SequentialProperties.v
- cava/Cava/ListUtils.v
These are helper lemmas from #482 that I'd like to add even though that PR is not getting merged. They're generally useful, so adding them will help us avoid duplicating work in the future.
> Helper lemmas

- cava/Cava2HDL.cabal
- silveroak-opentitan/aes/Acorn/AESExtraction.v
- silveroak-opentitan/aes/Acorn/AESSV.hs
- silveroak-opentitan/aes/Acorn/AddRoundKey.v
- silveroak-opentitan/aes/Acorn/ShiftRows.v
- silveroak-opentitan/aes/Acorn/SubBytes.v
- silveroak-opentitan/aes/Spec/AddRoundKey.v
- Extraction for ShiftRows SboxLut SubBytes AddRoundKey
- Small change to SubBytes to allow extraction of subcomponent aes_sbox_lut
- Spec/AddRoundKey.v change VectorDef to Vector import to solve extraction issues
> Extract combinational circuits

- cava/.gitignore
- cava/Cava/Netlist.v
- cava/Cava2HDL.cabal
- cava/Cava2SystemVerilog.hs
- cava/SystemVerilogUtils.hs
- cava/TestBench.hs
- investigations/sv-experiments/indexing.sv
- silveroak-opentitan/aes/Acorn/verilator.vlt
- tests/MuxTests.v
This changes the SystemVerilog interface generation to produce only packed arrays. Test-bench generation code changed accordingly.
> Generate SystemVerilog interfaces with only packed arrays

- cava/Cava/Acorn/NetlistGeneration.v
- cava/Cava/Signal.v
- cava/Cava2SystemVerilog.hs
Generate hex strings for bit-vector literals.
> Generate hex literals

- tests/Array.v
- tests/Makefile
- tests/TestsExtraction.v
- tests/TestsSV.hs
Test multidimensional array construction, see #501
> Add multidimensional array test

- silveroak-opentitan/aes/Acorn/AES256Equivalence.v
From merge of partially WIP CL, which was split into a separate issue.
> AES256Equivalence: remove FIXME

- silveroak-opentitan/aes/RunningInOpenTitan.md
- silveroak-opentitan/aes/copy_to_opentitan.sh
I'll perhaps add more automation with future scripts.
> Script and notes for running OpenTitan with our components

- cava/Cava/Acorn/CombinationalProperties.v
- cava/Cava/VectorUtils.v
- silveroak-opentitan/aes/Acorn/AES256Equivalence.v
- silveroak-opentitan/aes/Acorn/FullCipherEquiv_Assumptions.out
- silveroak-opentitan/aes/Acorn/FullCipherInverse_Assumptions.out
- silveroak-opentitan/aes/Acorn/ShiftRowsEquivalence.v
> Prove shift_rows circuit equivalent to spec

- silveroak-opentitan/aes/Acorn/README.md
> aes_sbox_lut performance comparison

- silveroak-opentitan/aes/Acorn/Cipher.v
An updated version of #485
I had to add more mkpair/unpair'ing, `key'` etc are used to avoid `key` etc notation.
> Add cipher based on loopDelayS

- silveroak-opentitan/aes/Acorn/README.md
> Document aes_add_round_key correspondance

- silveroak-opentitan/aes/Acorn/README.md
> Performance comparison of OT top-level block vs. Silver Oak

- silveroak-opentitan/aes/Acorn/Cipher.v
As discussed on Friday -- AES loop with all the signals that need to be accessed inside the loop body packaged up and treated as loop input so that their timing is correctly handled.
> Fix handling of loop input signals

- silveroak-opentitan/aes/Acorn/MixColumnsEquivalence.v
Follow-up to #535 
Just enough work on the `mix_single_column` equivalence lemma to factor out the right lemmas for `aes_mul2` and `aes_mul4`!
> Factor out mul2 and mul4

- cava/Cava2SystemVerilog.hs
> Compile time evaluation for fst and snd

- cava/Cava/Acorn/CavaClass.v
- cava/Cava/Acorn/CombinationalMonad.v
- cava/Cava/Acorn/NetlistGeneration.v
> Add local signal declaration for sharing

- cava/Cava/Acorn/CavaPrelude.v
> Change muxPair to assign result to local signal

- silveroak-opentitan/aes/Acorn/MixColumnsCircuit.v
Part of addressing #577 
The fix is simple: find places where an indexing expression would get copied, and pin it to a name with the use of `localSignal`, which should have identity function semantics for the proofs (in the `ident` monad).
@blaxill ~ please can you continue in other PRs to track down other places where duplication is occurring? I can tell from the generated SystemVerilog that we are duplicating vector literals, and in any case even though the size of generated file has been more than halved, I still feel it should be a lot shorter than 9939 lines. 
CC: @jadephilipoom ~ it might be worth adding a bit of proof automation for `localSignal`?
I am thinking of changing `indexAt` and `indexConst` to be circuits, which would then not require `localSignal` (see #575 )
> Reduce size of aes_mix_columns.sv from 25307 to 9939 lines

- cava/Cava/Acorn/Multistep.v
- tests/AccumulatingAdderEnable/AccumulatingAdderEnable.v
- tests/AccumulatingAdderEnable/ListProofs.v
- tests/Delay.v
> Port Delay.v and AccumulatingAdderEnable

- silveroak-opentitan/aes/Acorn/CipherControlCircuit.v
- silveroak-opentitan/aes/Acorn/Pkg.v
- silveroak-opentitan/aes/Acorn/SubBytesCircuit.v
Follow up PR has the logic that ties the cipher and cipher_control together
> Finish control loop

- silveroak-opentitan/aes/Acorn/CipherControlCircuit.v
> CipherControlCircuit: Correctly update signals

- docs/_layouts/default.html
Landing page: https://project-oak.github.io/silveroak/
> Simplify layout for wider text

- docs/index.md
> Link to interactive demo from root page

- demos/Makefile
- demos/tutorial.v
- docs/demo/tutorial.html
Progress on #609
Example 1 in the tutorial: a simple inverter circuit that I use to demonstrate some foundational Cava concepts.
As before, the HTML is auto-generated, so the best way to review this is to review the Coq source file, which has the prose descriptions as special comments. When you see a `coq:: none` tag at the end of a comment, it means that the Coq code between this comment and the next one will not show up in the resulting webpage.
> Inverter tutorial

- silveroak-opentitan/aes/copy_to_opentitan.sh
- silveroak-opentitan/aes/run_in_opentitan.sh
Simplify awk parts and add a script to run simulation.
> Update aes bash scripts

- cava/Cava/Core/Netlist.v
- demos/tutorial.v
- examples/AdderTree.v
- examples/FullAdderExample.v
- examples/NandGate.v
- examples/Sorter.v
- examples/UnsignedAdderExamples.v
- examples/xilinx/NandLUT.v
- examples/xilinx/XilinxAdderExamples.v
- examples/xilinx/XilinxAdderTree.v
- silveroak-opentitan/aes/Impl/AddRoundKeyNetlist.v
- silveroak-opentitan/aes/Impl/CipherControlNetlist.v
- silveroak-opentitan/aes/Impl/MixColumnsNetlist.v
- silveroak-opentitan/aes/Impl/ShiftRowsNetlist.v
- silveroak-opentitan/aes/Impl/SubBytesNetlist.v
- silveroak-opentitan/pinmux/Pinmux.v
- tests/AccumulatingAdderEnable/AccumulatingAdderEnable.v
- tests/Array.v
- tests/CountBy/CountBy.v
- tests/Delay.v
- tests/DoubleCountBy/DoubleCountBy.v
- tests/Instantiate.v
- tests/MuxTests.v
- tests/TestMultiply.v
- tests/xilinx/LUTTests.v
> Remove options argument from common case netlist generation

- cava/Cava/Extraction.v
- cava/Cava2HDL.cabal
- tests/Makefile
- tests/TestVecConstEq.v
- tests/TestsExtraction.v
- tests/TestsSV.hs
- tests/VecConstEq.v
Move `Example`s to `tests/` and create netlist and tb. c.f. #657
> add tests for VecConstEq

- cava/Cava/Core/CavaClass.v
- cava/Cava/NetlistGeneration/NetlistGeneration.v
- cava/Cava/Semantics/Combinational.v
> Remove vector slice from Cava class

- cava/Cava/Semantics/Simulation.v
- cava/Cava/Util/List.v
While writing the tutorial I realized we were completely missing proofs about the simulation of delays. This PR adds them for all four variants.
> Add proofs for simulating delays

- cava/Makefile
> Improve specification for Coq source files to ignore hidden files #686

- .github/workflows/build_all.yaml
- default.nix
- packages.nix
Further speed up changes can be made in the future.
> Split CI into multiple GitHub Action jobs

- silveroak-opentitan/aes/Impl/CanrightCircuit.v
- silveroak-opentitan/aes/Impl/CanrightEquivalence.v
- silveroak-opentitan/aes/Impl/Pkg.v
Simple equivalence by case computation
> Add canright equivalence to existing sbox

- investigations/vector/In.v
There are the proofs that didn't end up being used for DecoderProperties
> investigations/vector : Added proofs about InV

- cava/Cava/Lib/DecoderProperties.v
- cava/Cava/Util/BitArithmeticProperties.v
- cava/Cava/Util/Bool.v
> Decoder: proof of adjointness, reverse direction

- README.md
- cava/Cava2HDL.cabal
- examples/cava-examples.cabal
- silveroak-opentitan/aes/silveroak-aes.cabal
- silveroak-opentitan/pinmux/silveroak-pinmux.cabal
- tests/cava-tests.cabal
> Relax cabal GHC dependency and update documentation

- README.md
> Update README to include cabal dependency

- investigations/bedrock2/Aes/Aes.v
- investigations/bedrock2/Aes/AesProperties.v
- investigations/bedrock2/Aes/AesSemantics.v
These functions write input data to the AES block and (in my simplified version of the state machine) trigger the transition from IDLE to BUSY states.
> [investigations] Implement + prove aes_data_put and aes_data_put_wait

- Makefile
- README.md
- demos/tutorial.v
This adds a top level rule https://github.com/project-oak/silveroak/pull/777#issuecomment-832037017
> Add top level git submodule command

- cava/Cava/Lib/Lib.v
- cava/Cava/Lib/LibProperties.v
- cava/Cava/Lib/Multipliers.v
- cava/Cava/Lib/MultipliersProperties.v
- cava/Cava/Util/BitArithmeticProperties.v
- docs/reference.md
I needed this for the demo I'm developing, and it seems like a useful thing to have in the library anyway.
> Add a circuit that computes the square of a bitvector

- .github/workflows/build_all.yaml
> Cache third_party based on submodule commits

- investigations/ast/AST2.v
Just a quick example of casting to a first order representation to get the state. Alternatively doing it directly with the PHOAS rep. is also possible i think by selecting the right `var` type. The benefit of an explicit first order representation is that it might be useful for Jade's retiming work that benefits from a binderless inductive structure.
> Example of using first order representation to get state

- investigations/cava2/Expr.v
- investigations/cava2/Fib.v
- investigations/cava2/Makefile
- investigations/cava2/Semantics.v
- investigations/cava2/TLUL.v
- investigations/cava2/Types.v
Initial work on and inductively structured Cava
> Inductively structured Cava and TLUL sketch

- investigations/cava2/Expr.v
- investigations/cava2/Fib.v
- investigations/cava2/Semantics.v
- investigations/cava2/TLUL.v
Primitive operations are currently axiomatized as they may change
> Add untested TLUL register adapter 

- investigations/cava2/Expr.v
- investigations/cava2/Hmac.v
- investigations/cava2/Primitives.v
- investigations/cava2/Semantics.v
- investigations/cava2/Sha256.v
- investigations/cava2/TLUL.v
- investigations/cava2/Types.v
Currently untested. The intention is to also add a specification in pure gallina, and possibly state machine representation of the implementation to use in relating the control logic.
> Add SHA256 core internal to HMAC

- investigations/bedrock2/Uart/UartProperties.v
The proof was failing due to the change in AbsMMIO spec
> Fix a bug in UartProperties proof

- cava/Cava/Util/List.v
These might potentially be useful when reasoning about sub-traces.
> Add additional fold_left_accumulate' proofs

- investigations/cava2/Expr.v
- investigations/cava2/Fib.v
- investigations/cava2/Hmac.v
- investigations/cava2/Primitives.v
- investigations/cava2/Semantics.v
- investigations/cava2/Sha256.v
- investigations/cava2/TLUL.v
> Fix primitives

- investigations/cava2/Expr.v
- investigations/cava2/Fib.v
- investigations/cava2/Fifo.v
- investigations/cava2/Hmac.v
- investigations/cava2/Primitives.v
- investigations/cava2/Semantics.v
- investigations/cava2/Sha256.v
- investigations/cava2/_CoqProject
SHA padded-input-to-digest implementation now "correct" (correct output on test vector), everything else still untested (read buggy).
> Fix inner SHA256 circuit

- investigations/cava2/Sha256.v
`sha256_inner` was already working but some of the control logic around the cores was untested, this fixes everything: 
- Switched endianess of the padder
- Removed one of the digests from `sha256_inner` to simplify/optimise 
- Misc. control fixes
The circuit as a whole has a longer latency than the OpenTitan version because I haven't attempted to overlap any computation e.g. between the padder and the SHA rounds.
> Finish SHA256 circuit

- .github/workflows/build_all.yaml
Also:
- Cache cava/
- Simplify CI script
> Add hmac directory to CI

- investigations/cava2/Sha256.v
- Fixed incorrect padding for multiple blocks
- Switched padding done signal to latch (from single pulse)
> Fix multiblock SHA circuit

- cava2/Expr.v
- cava2/ExprProperties.v
Just some extra pieces that might come in useful when writing circuits -- I thought I might need these but ended up not needing them. Seems useful to have anyway.
> Add more comparators and fold_left templates

- cava2/Invariant.v
The `double_minimum` example from #932 tests that the invariant infrastructure can handle an abstract subcircuit by assuming that it exists and matches a certain specification, then proving that if those assumptions hold the `double_minimum` circuit is correct. However, I think it's also important to test that the infrastructure can nicely handle actually instantiating those proofs with concrete subcircuits, which is what this PR adds.
> Add concrete instantiations to abstract example

- firmware/IncrementWait/CavaIncrementDevice.v
- firmware/IncrementWait/RunIncrementWaitSoftwareOnCava.v
At the end I didn't use any spec. I suspect both [tlul_adapter_reg] and [incr] are just too simple to justify the overhead of a spec. Also, I can't think of a spec that is any different than the implementation.
> Increment device with TLUL

- cava2/Invariant.v
@blaxill and @fshaked , here's the lemmas I think you will need for the HMAC proof strategy we discussed just now. Basically, if you have a function that can turn a list of HMAC inputs into a list of SHA inputs, then you can feed the SHA inputs into these lemmas (particularly `postcondition_holds_big_step` and `invariant_holds_big_step`) in order to prove that e.g. the SHA postcondition holds on the latest output.
This way, the HMAC representation can be the list of HMAC inputs so far. In the invariant, you'd get the SHA inputs from the HMAC inputs, and the invariant would be something like:
```coq
fun hmac_inputs '(_, ... , _, sha_state) =>
let sha_inputs := sha_inputs_from_hmac_inputs hmac_inputs in
(* sha circuit state matches inputs *)
sha_state = snd (simulate' sha256 sha_inputs …
```
> Big-step lemmas for invariant framework

- examples/README.md
> Fix tiny typo
