project-oak/silveroak

- cava/Cava/Cava.v
- cava/Cava/Netlist.v
- cava/Cava2SystemVerilog.hs
- Separates CavaState into CavaState and Module, and adds alias Netlist for list Instance 
- Merges instance into primitive
I've attempted to separate some of the concerns of the netlist types, I've checked the generated systemverilog is the same.
> Simplify netlist types

- cava/.gitignore
- cava/Makefile
- cava/xorArrow_tb.sv
This PR adds code to check that the generated `xorArrow.sv` circuit can be compiled and uses it in a test bench (but currently the test does not fail if the functionality is wrong). It also generates a VCD waveform. 
```
./xorArrow.vvp
VCD info: dumpfile xorArrow.vcd opened for output.
VCD warning: $dumpvars: Unsupported argument type (vpiPackage)
0 input1 = 0, input2 = 0, output1 = 0
25 input1 = 1, input2 = 0, output1 = 1
35 input1 = 0, input2 = 1, output1 = 1
45 input1 = 1, input2 = 1, output1 = 0
55 input1 = 0, input2 = 0, output1 = 0
```
> Add SystemVerilog compilation for xorArrow.sv

- cava/Makefile
Works just for the Cava directory for now. Perhaps there is a way to use in information in the `.gitignore` of the parent directory.
> Clean .*.aux files in Cava

- cava/Makefile
- cava/README.md
- cava/verilator.vlt
Use `-rule` instead of `-msg` required by verilator version 4.030.
>  `-rule` instead of `-msg` required by verilator version 4.030

- cava/README.md
At some point the `nix` configuration files should install exactly this version of Verilator.
> Specify exactly the same version of Verilator as required by OpenTitan

- cava-examples/ExamplesExtraction.v
- cava-examples/FullAdder.v
- cava-examples/FullAdderNat.v
- cava-examples/UnsignedAdder.v
- cava-examples/UnsignedAdderNat.v
- cava/.gitignore
- cava/Cava/BitArithmetic.v
- cava/Cava/Cava.v
- cava/Cava/Examples.v
- cava/Cava/Extraction.v
- cava/Cava/Netlist.v
- cava/Cava2HDL.cabal
- cava/Cava2SystemVerilog.hs
- cava/_CoqProject
This reworks `unsignedAdder` to use the Vector type which allows us to explicitly encode bit-vector sizes in the type.
> Make adder used Vector type

- cava/Cava/Arrow/Instances/Netlist.v
- cava/Cava/Cava.v
- cava/Cava/Examples.v
- cava/Cava/Netlist.v
- cava/Cava2HDL.cabal
- cava/Cava2SystemVerilog.hs
`N` can't be extracted the way `Z` can (i.e. by silently converting to `Prelude.Integer`) so it is left as-is i.e. as `BinNum.N` which is then unpacked in the Haskell side.
Addresses issue #30
> Convert to using N instead of Z for net indexes and counting

- cava-examples/.gitignore
- cava-examples/AdderTree.v
- cava-examples/ExamplesExtraction.v
- cava-examples/ExamplesSV.hs
- cava-examples/Makefile
- cava-examples/_CoqProject
- cava-examples/adder8_3in_tb.sv
- cava-examples/verilator.vlt
This example checks that a three input adder of variable lengths works. Added verilator lint waiver to permit automatic extension of vectors for addition, added a small testbench and checked via Xilinx Vivado synthesis that this can be implemented (it can). Addressing #35
> A three input adder

- cava/cava/Cava/BitArithmetic.v
- cava/cava/Cava2HDL.cabal
- cava/cava/FixupAscii.hs
- cava/cava/Makefile
- cava/monad-examples/FullAdderNat.v
- cava/monad-examples/UnsignedAdderNat.v
Use library Coq.NArith.Ndigits for nat to bitvector conversion.
Also add a contributed proof for the list version of bit-vector conversion functions.
Addresses #51
> Use library Coq.NArith.Ndigits for nat to bitvector conversion.

- cava/cava/Cava/Arrow/Instances/Coq.v
- cava/cava/Cava/Arrow/Instances/Stream.v
- cava/cava/Cava/BitArithmetic.v
- cava/cava/Cava/Monad/Cava.v
- cava/monad-examples/AdderTree.v
- cava/monad-examples/Examples.v
Addresses #53 
Proofs for:
```coq
Lemma bits_of_nat_sized: forall n bv, nat_to_bitvec_sized n (bitvec_to_nat bv) = bv.
Lemma nat_of_bits: forall v, bitvec_to_nat (nat_to_bitvec v) = v.
Lemma nat_of_bits_sized: forall (v : nat),
bitvec_to_nat (nat_to_bitvec_sized (N.size_nat (N.of_nat v)) v) = v.
```
Still to think about:
```coq
Lemma nat_of_bits_sized_n: forall n (v : nat),
bitvec_to_nat (nat_to_bitvec_sized n v) = v.
Admitted.
```
> Proofs about nat to bitvector conversion

- cava/arrow-examples/ArrowExamples.v
- cava/cava/Cava/Arrow/Arrow.v
- cava/cava/Cava/Arrow/Instances/Coq.v
- cava/cava/Cava/Arrow/Instances/Netlist.v
- cava/cava/Cava/Arrow/Instances/Stream.v
- cava/cava/Cava/Monad/Cava.v
- cava/cava/Cava/Netlist.v
- cava/cava/Cava2HDL.cabal
- cava/cava/Cava2SystemVerilog.hs
This reintroduces 'shape' from Cava v2, allowing named ports of arbitrary shape and for the shape to be reused in higher level representations e.g. arrows. 
It also separates primitives from their bindings, which will allow the primitives to be reused in Netlist DSLs (and other DSLs), that might not want to directly specify `N` bindings. 
Also temporarily remove the existing Netlist DSL, a newer iteration to be reintroduced in follow up PRs.
> Reintroduce shape from v2 and separate primitives from binding sites

- cava/Makefile
- cava/arrow-examples/ArrowExamples.v
- cava/cava/Cava/Arrow/Instances/Coq.v
- cava/cava/Cava/Arrow/Instances/Netlist.v
- cava/cava/Cava/Extraction.v
- cava/cava/Cava2HDL.cabal
- cava/cava/_CoqProject
The Netlist Arrow instance is currently restricted to one dimensional bitvectors, and use some intermediate types that will be removed in the future.
> Enable Arrows with the updated Netlist

- cava/cava/Cava/Arrow/Arrow.v
- cava/cava/Cava/Arrow/Syntax.v
- cava/cava/_CoqProject
This adds arrow notation. It is still missing a key part of the compilation to generalized arrows which I am continuing to work on.
Some of the syntax will simplify further when the compilation pass is done. Items here built as `kappa` types are left as `kappa` types and require separate notation, but they directly reduce to an arrow in future and not require separate notation.
> Add Arrow notation

- cava/cava/Cava/BitArithmetic.v
- cava/cava/Cava/Monad/Cava.v
- cava/cava/Cava/Monad/UnsignedAdders.v
- cava/monad-examples/AdderTree.v
- cava/monad-examples/FullAdderNat.v
As we process lager numbers it is going to be much more efficient to represent them in a binary way using `N` rather than `nat`. I can't immediately work out how to re-do one of the proofs with `N` instead of `nat` for the rule `Nat.pow_succ_r` so admitting for now.
> Switch from nat to N for values convertible to bit-vectors

- cava/cava/Cava/Monad/Cava.v
- cava/cava/Cava/Monad/UnsignedAdders.v
- cava/monad-examples/AdderTree.v
- cava/monad-examples/UnsignedAdderExamples.v
- cava/monad-examples/testbench/adder_tree4_8_tb.sv
This simplifies semantic and proofs, and I think we should explicitly separate out the process of `mod`-ing values to shave off bits.
> Make adder semantics assume bit-growth implicitly

- cava/arrow-examples/ArrowExamples.v
- cava/cava/Cava/Arrow/Instances/Netlist.v
- cava/cava/Cava/Monad/Cava.v
- cava/cava/Cava/Monad/Combinators.v
- cava/cava/Cava/Netlist.v
- cava/cava/Cava2SystemVerilog.hs
- cava/monad-examples/AdderTree.v
- cava/monad-examples/FullAdder.v
- cava/monad-examples/FullAdderNat.v
- cava/monad-examples/NandGate.v
- cava/monad-examples/UnsignedAdder.v
- cava/monad-examples/UnsignedAdderExamples.v
- cava/monad-examples/UnsignedAdderNat.v
This PR is a first attempt at adding a mechanism for describing circuit interfaces which will allow us to do things like automate the generation of test benches. Several things are not right with the current approach but it is a step forward from the current ad hoc port wiring process.
The `singalTy` function does not seem to work for tuples of tuples, as described in the `Cava.v` files. Currently the adder tree example uses a workaround for this.
This PR no longer associates port net numbers with the port declarations . Instead, the association between port names and internal nets is made using four wiring components. This means the arrow examples don't generate working SystemVerilog now because I was not able to adjust the arrow code to use to new components. If this is too much of a …
> Add circuit interface mechansim

- cava/cava/Cava/Monad/Cava.v
- cava/cava/Cava/Netlist.v
- cava/cava/Cava2SystemVerilog.hs
- cava/monad-examples/AdderTree.v
This adds support for multi-dimensional bit-vectors used as the *inputs* to circuits to be used for circuit netlist generation and for test-bench generation. Support for multi-dimensional output bit-vectors will follow in the separate PR.
Partly addresses #77
> Add support for multi-dimensional input bit-vectors

- cava/arrow-examples/ArrowExamples.v
- cava/arrow-examples/ArrowExamplesSV.hs
- cava/arrow-examples/Extraction.v
- cava/arrow-examples/FeedbackNand.v
- cava/arrow-examples/Makefile
- cava/arrow-examples/Nand.v
- cava/arrow-examples/Xor.v
- cava/arrow-examples/_CoqProject
- cava/arrow-examples/testbench/feedbackNandArrow_tb.sv
- cava/cava/Cava/Arrow/Instances/Netlist.v
- cava/cava/Cava/Monad/Cava.v
- cava/cava/Cava/Netlist.v
This updates arrows for the new netlist types and adds a few functions port functions.
I also moved your existing `numberBitVec` `numberPort` functions into Netlist.v so they can be used for arrows too. I added a `flattenBitVec` function as I was having trouble getting the classes to resolve when the value I had was not concrete/was dependent on a sub call, but that might have been a limitation in my Coq understanding. 
~~There is one issue left, the inputs/outputs aren't connected (see below), I couldn't see how to connect them up with mkModule now- @satnam6502 do I need to use the new CircuitInterface for this? thanks~~ I think I know what to do, working on this now
~~~
module xorArrow(
input logic input1,
input logic input2,
output logic output1
);
timeunit 1ns; timeprecision 1ns; …
> Update Arrow/Instances/Netlist.v for the new netlist types

- cava/Makefile
- cava/_CoqProject
- cava/arrow-examples/ArrowExamples.v
- cava/arrow-examples/FeedbackNand.v
- cava/arrow-examples/Xor.v
- cava/arrow-examples/_CoqProject
- cava/monad-examples/FullAdderNat.v
- cava/monad-examples/MonadExtraction.v
- cava/monad-examples/_CoqProject
- cava/monad-examples/xilinx/XilinxExtraction.v
- cava/monad-examples/xilinx/_CoqProject
@blaxill as part of this change I put the examples (including the arrow examples) into their own libraries with a name other than the default `Lib`.
Now we can start Visual Studio code from the top level caca directory and the `_CoqProject` there makes all the cava source and the library source available in Visual Studio code.
> Add a _CoqProject to use for vscoq for Visual Studio Code

- cava/tests/xilinx/LUTTests.v
- cava/tests/xilinx/Makefile
- cava/tests/xilinx/VivadoExtraction.v
- cava/tests/xilinx/VivadoTestsSV.hs
- cava/tests/xilinx/_CoqProject
- cava/tests/xilinx/lutNAND_tb.tcl
This moves the LUT tests form `monad-examples/xilinx` to `tests/xilinx` and also tests INV and AND2 individually. Tests are run with the Xilinx xsim simulator. The testbench generator now produces a tcl script for driving the simulation and producing a VCD waveform. Right now we can't run these tests in CI until we can work out a way of running SystemVerilog simulations in our CI framework that work with the UNISIM library.
```console
xvlog -sv lut1_inv.sv lut1_inv_tb.sv
INFO: [VRFC 10-2263] Analyzing SystemVerilog file "/usr/local/google/home/satnam/oak-hardware/cava/tests/xilinx/lut1_inv.sv" into library work
INFO: [VRFC 10-311] analyzing module lut1_inv
INFO: [VRFC 10-2263] Analyzing SystemVerilog file "/usr/local/google/home/satnam/oak-hardware/cava/tests/xilinx/lut1_inv_tb.sv" into …
```
> Create tests and LUT1 INV and LUT2 AND

- cava/cava/Cava/Monad/Cava.v
- cava/cava/Cava/Netlist.v
- cava/cava/Cava2SystemVerilog.hs
- cava/tests/xilinx/LUTTests.v
- cava/tests/xilinx/Makefile
- cava/tests/xilinx/VivadoTestsSV.hs
Added LUT4 to netlist data-type and monad API for Cava and produced a small test to check against config LSB/MSB errors.
```console
xsim --tclbatch lut4_and_tb.tcl lut4_and_tb_sim
****** xsim v2018.3 (64-bit)
**** SW Build 2405991 on Thu Dec  6 23:36:41 MST 2018
**** IP Build 2404404 on Fri Dec  7 01:43:56 MST 2018
** Copyright 1986-2018 Xilinx, Inc. All Rights Reserved.
source xsim.dir/lut4_and_tb_sim/xsim_script.tcl
Vivado Simulator 2018.3
Time resolution is 1 ps
source lut4_and_tb.tcl
INFO: HDL object /lut4_and_tb/i0_vectors is an unpacked array. VCD does not support unpacked array type according to IEEE LRM 1800-2009, section21.7.5.
INFO: HDL object /lut4_and_tb/i1_vectors is an unpacked array. VCD does not support unpacked array type according to IEEE LRM 1800-2009, section21.7.5. …
```
> Implement and test LUT4

- cava/cava/.gitignore
- cava/cava/Cava/Extraction.v
- cava/cava/Cava2HDL.cabal
- cava/cava/FixupHaskell.hs
- cava/cava/Makefile
This changes the extraction technique to add a comment to Haskell files to indicated they have been auto-generated (so don't hand edit).
> Add comment to auto-generated Haskell files

- cava/cava/Cava/Monad/Cava.v
- cava/cava/Cava/Netlist.v
- cava/cava/Cava2SystemVerilog.hs
- cava/tests/xilinx/Makefile
- cava/tests/xilinx/verilator.vlt
Signed-off-by: Satnam Singh <satnam@google.com>
Now all component instantiations (except for primitive gates) have the port name used in the instantiation. The Xilinx gates have been removed as explicit enteries in `Netlist` and instead there is now a generic `Component` constructor for building SystemVerilog instantiations.
> Add port names to component instantiations

- cava/cava/Cava/Arrow/Instances/Netlist.v
- cava/cava/Cava/Extraction.v
- cava/cava/Cava/Monad/Cava.v
- cava/cava/Cava/Netlist.v
- cava/cava/Cava/Signal.v
- cava/cava/Cava/Types.v
- cava/cava/Cava2HDL.cabal
- cava/cava/Cava2SystemVerilog.hs
- cava/cava/_CoqProject
- cava/monad-examples/Multiplexers.v
This PR changes the wire representation from `N` to the structured `Signal` type which helps us generate better looking SystemVerilog and sets us up better for vector slicing expressions.
> Convert the wire representation from N to Signal

- cava/arrow-examples/SyntaxExamples.v
- cava/cava/Cava/Arrow/Arrow.v
- cava/cava/Cava/Arrow/Instances/Combinational.v
- cava/cava/Cava/Arrow/Instances/Constructive.v
- cava/cava/Cava/Arrow/Instances/Netlist.v
- cava/cava/Cava/Arrow/Kappa/Syntax.v
- cava/cava/Cava/Netlist.v
- cava/cava/Cava2HDL.cabal
- cava/cava/FixupHaskell.hs
- cava/cava/Makefile
Currently this generates a dummy Netlist instance `IndexAlt`. After switching Netlist `list`s back to vectors an indexing function will be created and this netlist constructor can be removed.
> Add LUTs and multidimensional indexing to Arrows

- cava/arrow-examples/ArrowAdder.v
- cava/arrow-examples/Concatenative/Examples.v
- cava/arrow-examples/Mux2_1.v
- cava/cava/Cava/Netlist.v
- cava/cava/Cava/Signal.v
- cava/cava/Cava2SystemVerilog.hs
- cava/monad-examples/AdderTree.v
- cava/monad-examples/FullAdder.v
- cava/monad-examples/Multiplexers.v
- cava/monad-examples/NandGate.v
- cava/monad-examples/UnsignedAdderExamples.v
- cava/monad-examples/xilinx/NandLUT.v
- cava/monad-examples/xilinx/XilinxAdderExamples.v
- cava/monad-examples/xilinx/XilinxAdderTree.v
- cava/tests/xilinx/LUTTests.v
Signed-off-by: Satnam Singh <satnam@google.com>
The circuit interface mechanism is tweaked to add information and the names and edge-behaviour of clock and reset inputs.
> Support negative edges for clock and reset

- cava/cava/Cava/Arrow/Arrow.v
- cava/cava/Cava/Arrow/Instances/Combinational.v
- cava/cava/Cava/Arrow/Instances/Constructive.v
- cava/cava/Cava/Arrow/Instances/Netlist.v
- cava/cava/Cava/Netlist.v
- cava/cava/Cava/Types.v
- cava/opentitan/pinmux/Makefile
- cava/opentitan/pinmux/Pinmux.v
- cava/opentitan/pinmux/_CoqProject
A first cut at a stub for the top-level pinmux. Several dummy definitions for now to accommodate a new signal value to represent uninterpreted types.
> Pinmux top level stub

- cava/arrow-examples/ArrowAdder.v
- cava/arrow-examples/Concatenative/Examples.v
- cava/arrow-examples/Mux2_1.v
- cava/cava/Cava/Netlist.v
- cava/cava/Cava/Signal.v
- cava/cava/Cava/Types.v
- cava/cava/Cava2SystemVerilog.hs
- cava/monad-examples/AdderTree.v
- cava/monad-examples/FullAdder.v
- cava/monad-examples/Multiplexers.v
- cava/monad-examples/NandGate.v
- cava/monad-examples/UnsignedAdderExamples.v
- cava/monad-examples/xilinx/NandLUT.v
- cava/monad-examples/xilinx/XilinxAdderExamples.v
- cava/monad-examples/xilinx/XilinxAdderTree.v
- cava/opentitan/pinmux/Makefile
- cava/opentitan/pinmux/Pinmux.v
- cava/tests/xilinx/LUTTests.v
Several changes:
* The `Shape` constructors don't need to be used in circuit interfaces, leading to much clearer interface descriptions. Several typeclasses that are no longer needed are deleted in the PR.
* The port specifications are now directly in terms of the `PortDeclaration` type e.g. `mkPort "wombat" Bit`.
* A stub definition for the pinmux has been started.
> Remove Shape constructors from interface specifications.

- cava/cava/Cava/Cava.v
- cava/cava/Cava/Extraction.v
- cava/cava/Cava/Monad/CavaClass.v
- cava/cava/Cava/Monad/CavaMonad.v
- cava/cava/Cava/Monad/CombinationalMonad.v
- cava/cava/Cava/Monad/Combinators.v
- cava/cava/Cava/Monad/NetlistGeneration.v
- cava/cava/Cava/Monad/UnsignedAdders.v
- cava/cava/Cava/Monad/XilinxAdder.v
- cava/cava/Cava2HDL.cabal
- cava/cava/_CoqProject
- cava/monad-examples/AdderTree.v
- cava/monad-examples/FullAdder.v
- cava/monad-examples/FullAdderNat.v
- cava/monad-examples/Multiplexers.v
- cava/monad-examples/NandGate.v
- cava/monad-examples/UnsignedAdderExamples.v
- cava/monad-examples/xilinx/NandLUT.v
- cava/monad-examples/xilinx/XilinxAdderExamples.v
- cava/monad-examples/xilinx/XilinxAdderTree.v
- cava/opentitan/pinmux/Pinmux.v
- cava/tests/xilinx/LUTTests.v
Signed-off-by: Satnam Singh <satnam@google.com>
This breaks some large `.v` files into smaller modules, and simplifies the imports for the Cava core and the monad kernel (in preparation for further refactoring).
> Refactor modules for Cava monad kernel

- cava/cava/Cava/Arrow/Arrow.v
- cava/cava/Cava/Arrow/Instances/Combinational.v
- cava/cava/Cava/Arrow/Instances/Constructive.v
- cava/cava/Cava/Arrow/Instances/Netlist.v
- cava/cava/Cava/Arrow/Kappa/Kappa.v
- cava/cava/Cava/Arrow/Kappa/Syntax.v
- Use nat vs N as indices.
- Rename concat to append.
- Add concat and split.
> Update Arrow.Cava vector functions

- cava/cava/Cava/Arrow/Arrow.v
- cava/cava/Cava/Arrow/Instances/Combinational.v
- cava/cava/Cava/Arrow/Instances/Constructive.v
- cava/cava/Cava/Arrow/Instances/Netlist.v
- cava/cava/Cava/Arrow/Kappa/Kappa.v
- cava/cava/Cava/Arrow/Kappa/Syntax.v
Change the type of `append` from `n + 1` to `S n`. `S n` is
definitionally correct and so requires less work in proving type
equality.
> Use the usual Fst Snd naming convention in Kappa

- cava/cava/Cava/Monad/CavaClass.v
- cava/cava/Cava/Monad/CombinationalMonad.v
- cava/cava/Cava/Monad/Combinators.v
- cava/cava/Cava/Monad/NetlistGeneration.v
- cava/cava/Cava/Monad/UnsignedAdders.v
- cava/cava/Cava/Monad/XilinxAdder.v
- cava/cava/Cava/Netlist.v
- cava/cava/Cava/Signal.v
- cava/cava/Cava/Types.v
- cava/cava/Cava/VectorUtils.v
- cava/monad-examples/AdderTree.v
- cava/monad-examples/Multiplexers.v
- cava/monad-examples/UnsignedAdderExamples.v
- cava/monad-examples/xilinx/XilinxAdderTree.v
Having the `vec` parameter in the monad-kernel typeclass was causing a lot of issues even though it meant we did not need to smash vectors. This PR removes this level of parameterization and uses `Vector.t` instead which leads to simpler and easier to use interfaces for circuits. The key functions for smashing and wrapping up smashed values are in the `Types.v` file.
> Switch Cava monad kernel to use smashed vectors

- cava/cava/Cava/Monad/CavaClass.v
- cava/cava/Cava/Monad/CombinationalMonad.v
- cava/cava/Cava/Monad/NetlistGeneration.v
- cava/cava/Cava/Netlist.v
- cava/cava/Cava2SystemVerilog.hs
- cava/monad-examples/AdderTree.v
- cava/monad-examples/ExamplesSV.hs
- cava/monad-examples/Makefile
- cava/monad-examples/MonadExtraction.v
- cava/monad-examples/Sorter.v
- cava/monad-examples/_CoqProject
The leaf component I want to use for a recursive Batcher's bitonic merger/sorter.
The two sorter works in Verilog simulation.
However, I expected the proof of the two sorter's correctness to be easy, but it unfolds in a complicated way.
The next step is to define riffile, but the dependent `Vector.t` types need to be ironed out.
> A two sorter example.

- cava/cava/Cava/Monad/CavaClass.v
- cava/cava/Cava/Monad/CombinationalMonad.v
- cava/cava/Cava/Monad/NetlistGeneration.v
- cava/cava/Cava/Netlist.v
- cava/cava/Cava/Signal.v
- cava/cava/Cava2SystemVerilog.hs
- cava/monad-examples/Multiplexers.v
- cava/monad-examples/Sorter.v
This improves the quality of the generated SystemVerilog for many uses of dynamic and static indexing.
There is still an explosion in the unsmshing and de-literalization process that makes the two sorter example not work out well (but still generated valid SystemVerilog that is synthesis equivalent to a good implementation). Slicing also still needs to be supported. These two points will be addressed in a subsequent PR.
> Recover smashed arrays in Haskell back-end

- cava/cava/Cava/Netlist.v
- cava/cava/Cava2HDL.cabal
- cava/cava/Cava2SystemVerilog.hs
This PR improves the quality of the generated SystemVerilog for several of our example circuits by adding mode smashed vector recovery optimizations. For example:
For the Cava:
```coq
Definition muxBus4_8 {m bit} `{Cava m bit} 
(vsel: Vector.t (smashTy bit (BitVec Bit 8)) 4 *
Vector.t bit 2) :
m (smashTy bit (BitVec Bit 8)) :=
let (v, sel) := vsel in
ret (indexAt v sel).
```
Generated SystemVerilog:
```verilog
module muxBus4_8(
input   logic[1:0] sel,
input   logic[7:0] i[4],
output   logic[7:0] o
);
timeunit 1ns; timeprecision 1ns;
logic zero;
logic one;
// Constant nets
assign zero = 1'b0;
assign one = 1'b1;
assign o = i[sel];
endmodule
```
For the Cava:
```coq
Definition twoSorter {m bit} `{Cava m bit} {n}
(ab: Vector.t (smashTy bit (BitVec Bit n)) 2) :
m (Vector.t (Vector.t bit n) 2) …
```
> Improve quality of SystemVerilog generated for indexing vectors

- cava/cava/Cava/Monad/CavaClass.v
- cava/cava/Cava/Monad/CombinationalMonad.v
- cava/cava/Cava/Monad/NetlistGeneration.v
- cava/cava/Cava/Monad/UnsignedAdders.v
- cava/cava/Cava/VectorUtils.v
- cava/cava/Cava2SystemVerilog.hs
- cava/monad-examples/AdderTree.v
- cava/monad-examples/UnsignedAdderExamples.v
Vector slices are now recovered. The adder with no bit-growth is no longer in the kernel of the monad backend but is defined as a library function using indexing. The generated SystemVerilog for one of the adder trees shows correct slicing that captures the truncation required for no bit-growth.
```verilog
module adder_tree4_8(
input   logic[7:0] inputs[4],
output   logic[7:0] sum
);
timeunit 1ns; timeprecision 1ns;
logic zero;
logic one;
logic[8:0] v0;
logic[8:0] v1;
logic[8:0] v2;
// Constant nets
assign zero = 1'b0;
assign one = 1'b1;
assign sum = v2[7:0];
assign v2 = v0[7:0] + v1[7:0];
assign v1 = inputs[2] + inputs[3];
assign v0 = inputs[0] + inputs[1];
endmodule
```
> Recover slice indexing for smashed vectors

- cava/arrow-examples/ArrowAdder.v
- cava/arrow-examples/Mux2_1.v
- cava/arrow-examples/SyntaxExamples.v
- cava/arrow-examples/UnsignedAdder.v
- cava/cava/Cava/Arrow/CavaArrow.v
- cava/cava/Cava/Arrow/CavaExpression.v
- cava/cava/Cava/Arrow/CavaNotation.v
- cava/cava/Cava/Arrow/CombinationalArrow.v
- cava/cava/Cava/Arrow/NetlistArrow.v
- cava/cava/Cava/Arrow/PropArrow.v
- Also add method for delimiting modules, currently unused.
> Close Arrow expressions so that variables are out of scope for splices

- cava/cava/Cava/Arrow/ArrowExport.v
- cava/cava/Cava/Arrow/EvaluationArrow.v
- cava/cava/Cava/Extraction.v
- cava/cava/Cava2HDL.cabal
- cava/cava/_CoqProject
This evaluator is modelled as a transition function from 'input -> state -> (output, state)'.
It should be capable of handling all loop/delay/etc elements. The
semantics are currently that looping elements are evaluated once- i.e.
prevention of combinational loops is intended to be handled by external
lemmas. In the future this evaluator could be extended to handle combinational
loops that can be proved to converge after 'n' loops within the same cycle, if
this would be a useful property.
The intention is to remove the 'CombinationalArrow' in a future PR, with 'stateless_evaluation' from `EvaluationArrow` added here to replace evaluation from `CombinationalArrow`.
> Add evaluator for Arrows

- cava/arrow-examples/ArrowExtraction.v
- cava/arrow-examples/Combinators.v
- cava/arrow-examples/UnsignedAdder.v
- cava/arrow-examples/_CoqProject
- cava/arrow-lib/ClosureConversion.v
- cava/arrow-lib/Kappa.v
- cava/cava/Cava/Arrow/CavaExpression.v
- cava/cava/Cava/Arrow/CavaNotation.v
- cava/cava/Cava/Arrow/EvaluationArrow.v
This adds an automated process for proving a circuit built from expressions containing no loops and only stateless subexpressions is stateless. 
This also renames the `Library` to `Combinators`- I didn't use `ArrowCombinators` as the file is under `arrow-examples/` rather than the main `cava` directory.
> Add expression-arrow automated proof of stateless circuits

- cava/arrow-examples/Aes/pkg.v
- cava/arrow-examples/Aes/sbox.v
- cava/arrow-examples/ArrowExtraction.v
- cava/arrow-examples/Combinators.v
- cava/cava/Cava/Arrow/ArrowExport.v
- cava/cava/Cava/Arrow/CavaArrow.v
- cava/cava/Cava/Arrow/CavaExpression.v
- cava/cava/Cava/Arrow/CavaExpressionProp.v
- cava/cava/Cava/Arrow/CavaNotation.v
- cava/cava/Cava/Arrow/CombinationalArrow.v
- cava/cava/Cava/Arrow/EvaluationArrow.v
- Don't use `lia` in `arg_length` definition
- Use `Strategy opaque` to stop unnecessary unfolding
> Unfolding/rewriting performance fixes for CavaExpr

- cava/cava/Cava/Arrow/ArrowExport.v
- cava/cava/Cava/Arrow/ArrowKind.v
- cava/cava/Cava/Arrow/CavaArrow.v
- cava/cava/Cava2HDL.cabal
- cava/cava/_CoqProject
In preparation of adding more types to arrows, including "uninterpretable" and also custom types. 
Also adds a non-axiom and transparent `UIP_refl_kind` implementation.
> Move Arrow Kind to new module

- cava/arrow-examples/Aes/sbox.v
- cava/arrow-examples/Combinators.v
- cava/arrow-lib/Arrow.v
- cava/arrow-lib/ClosureConversion.v
- cava/arrow-lib/Equiv.v
- cava/arrow-lib/Kappa.v
- cava/arrow-lib/_CoqProject
- cava/cava/Cava/Arrow/ArrowKind.v
- cava/cava/Cava/Arrow/CavaExpression.v
- cava/cava/Cava/Arrow/CavaExpressionProp.v
- cava/cava/Cava/Arrow/CavaNotation.v
In preparation of removing redundant CavaExpr expression in favour of arrow-lib Kappa, which CavaExpr currently immediately desugars to.
> Add non-recursive let and refactor Arrow code

- cava/arrow-examples/Aes/pkg.v
- cava/arrow-examples/Aes/sbox.v
- cava/arrow-examples/Aes/sbox_canright_pkg.v
- cava/arrow-examples/ArrowAdderTutorial.v
- cava/arrow-examples/Mux2_1.v
- cava/arrow-examples/UnsignedAdder.v
- cava/arrow-lib/Arrow.v
- cava/arrow-lib/Kappa.v
- cava/cava/Cava/Arrow/ArrowKind.v
- cava/cava/Cava/Arrow/CavaArrow.v
- cava/cava/Cava/Arrow/CavaExpression.v
- cava/cava/Cava/Arrow/CavaNotation.v
- cava/cava/Cava/Arrow/CombinationalArrow.v
- cava/cava/Cava/Arrow/EvaluationArrow.v
- cava/cava/Cava/Arrow/NetlistArrow.v
- Add evaluation semantics for CavaExpr now `@Kappa Cava` combinational expressions
- Standardise CavaArrow methods to have right most unit (reduces the amount of conversion functions needed).
This moves towards a DSL tower of
1) CavaExpr based on Kappa caluculus
2) CavaArrow circuit DSL design directed by arrows
3) The shared netlist representation
Variables get removed from 1 to 2, types get simplified between 2 to 3.
> Remove redundant CavaExpr in favor of Kappa

- cava/cava/Cava/Netlist.v
- cava/cava/Cava/Signal.v
- cava/cava/Cava/Types.v
- cava/cava/Cava2SystemVerilog.hs
- cava/opentitan/pinmux/Makefile
- cava/opentitan/pinmux/Pinmux.v
- cava/opentitan/pinmux/PinmuxExtraction.v
- cava/opentitan/pinmux/PinmuxSV.hs
- cava/opentitan/pinmux/_CoqProject
This PR allows blax-box components to be instantiated from circuit interface declarations. The PR demonstrates it use for instantiating the pinmux_reg_top component:
```
Definition pinmux_reg_top_Interface :=
sequentialInterface "pinmux_reg_top"
"clk_i" PositiveEdge "rst_ni" NegativeEdge
(mkPort "tl_i" (ExternalType "tlul_pkg::tl_h2d_t"),
mkPort "devmode_i" Bit)
(mkPort "tl_o" (ExternalType "tlul_pkg::tl_d2h_t"),
mkPort "reg2hw" (ExternalType "pinmux_reg_pkg::pinmux_reg2hw_t"))
[].
...
const1 <- one ;;
'(tl_o, reg2hw) <- blackBox pinmux_reg_top_Interface (tl_i, const1) ;;
```
This generates SystemVerilog for the black-box component:
```verilog
pinmux_reg_top inst_4 (.clk_i(clk_i),.rst_ni(rst_ni),.tl_i(tl_i),.devmode_i(one),.tl_o(ext_0),.reg2hw(ext_1));
```
although modules that use …
> Implement declaration and instantiation of black-box components

- cava/_CoqProject
> Fix coq-ext-lib module import name

- cava/arrow-examples/Aes/sbox_canright_pkg.v
- cava/arrow-examples/ArrowAdderTutorial.v
- cava/arrow-examples/Mux2_1.v
- cava/arrow-examples/SyntaxExamples.v
- cava/arrow-examples/UnsignedAdder.v
- cava/cava/Cava/Arrow/CavaExpression.v
- cava/cava/Cava/Arrow/CombinationalArrow.v
- cava/cava/Cava/Arrow/PropArrow.v
This is a cleanup of an avenue I was testing for faster execution. Uses default values instead of working within an option monad. I don't think it actually is faster but the representations should be equivalent and this one is simpler.
> Simplify combinational evaluator

- fpga/zcu104/opentitan/Makefile
- fpga/zcu104/opentitan/clkgen_zcu104.sv
- fpga/zcu104/opentitan/pins_zcu104.xdc
- fpga/zcu104/opentitan/top_earlgrey_zcu104.core
- fpga/zcu104/opentitan/top_earlgrey_zcu104.sv
- fpga/zcu104/opentitan/vivado_hook_opt_design_post.tcl
- fpga/zcu104/opentitan/vivado_hook_write_bitstream_pre.tcl
The Makefile overwrites the currently checked out OpenTitan design is target the Xilinx ZCU104 FPGA board.
```console
$ make
```
copies the files over. The design is build with:
```console
$ fusesoc --cores-root . run --target=synth lowrisc:systems:top_earlgrey_zcu104
```
and programmed with
```console
$ fusesoc --cores-root . pgm lowrisc:systems:top_earlgrey_zcu104:0.1
```
Which should display a message like this on the UART:
[opentitan-oldpinxver-zcu104](https://user-images.githubusercontent.com/6164339/90307692-87e66600-de8d-11ea-8211-49386d45bd45.png)
Current work at commit 783edaf444eb0d9eaf9df71c785089bffcda574e (but not later commits yet).
> Port of OpenTitan to the Xilinx XCV104 FPGA board

- .gitmodules
Adds OpenTitan to `third_party/opentitan` as a submodule, the opentitan directory is currently not used in any build scripts.
> Add OpenTitan at commit 783edaf444eb0d9eaf9df71c785089bffcda574e

- cava/arrow-examples/.gitignore
- cava/arrow-examples/Aes/pkg.v
- cava/arrow-examples/Aes/sbox.v
- cava/arrow-examples/Aes/unrolled_cipher.v
- cava/arrow-examples/ArrowExtraction.v
- cava/arrow-examples/Combinators.v
- cava/arrow-examples/Main.hs
- cava/arrow-examples/_CoqProject
- Currently incorrect result, key expansion is likely wrong as code was converted from stateful to stateless. A separate PR will add a naive direct implementation of key expansion.
- Sbox_lut is temporarily disabled to make Haskell extraction and evaluation easier
> Update converted OpenTitan AES

- cava/README.md
- third_party/Makefile
- third_party/README.md
I propose we have a `Makefile` in `third_party` that will check out and build the Git submodules.
I'll leave it to @blaxill to update the cloud-build YAML to invoke this.
> Add Makefile for checking out and building Git submodules

- cava/arrow-lib/Arrow.v
Revised version of #207. As per discussion in that PR, I left the arrow laws unchanged and derived the continuation-style versions as separate lemmas.
> Derive arrow-law lemmas with continuations

- .gitmodules
When I tried to do a fresh clone from my new corp laptop, I was getting "repository not found" errors during submodule initialization. This change fixed the issue.
> Remove trailing slash from submodule URLs

- .gitignore
The autogenerated file `.nia.cache` showed up in my `git status`. This PR prevents it from doing that again!
> Add .nia.cache to .gitignore

- cava/cava/Cava/ListUtils.v
- cava/cava/Cava/Monad/Combinators.v
- cava/cava/Cava/VectorUtils.v
- cava/cava/_CoqProject
- cava/monad-examples/AdderTree.v
- cava/monad-examples/xilinx/XilinxAdderTree.v
Here's the tree combinator proofs I walked through in the last meeting. I'll recap here anyway for archival purposes. The main punchlines are the proofs `tree_equiv` and `treeList_equiv`, both in `Combinators.v`, which serve as the proofs of functional correctness for the preexisting tree combinator operations. In order to prove them, I also needed various proofs about vectors and lists which now live in `VectorUtils.v` and the new file `ListUtils.v`. I created a helper tactic for lists that's pretty generic, so I went ahead and made it exported from `ListUtils.v` and added some tests for it to make it more robust.
Proving the vector tree combinator as-is was tricky because of vector size coercions, so I created a new definition `resize` that, given a vector and a proof that its is equal …
> Tree combinator proofs

- cava/cava/Cava/Monad/Combinators.v
- cava/cava/Cava/Tactics.v
I wrote a useful tactic for removing "destructing lets" (e.g. `let '(x, y) := p in ...`) to do the tree combinator proofs before, and found myself having need of it again! So I put it in the `Cava/Tactics.v` file and added some tests to allow broader use.
> Generalize destruct_pair_let tactic

- cava/cava/Cava/Arrow/CircuitFunctionalEquivalence.v
- cava/cava/Cava/Arrow/CircuitProp.v
I've been working on getting an AES top-level proof (top-level circuit proven assuming its subroutines are correct) put together, and in the process I found it useful to:
- change the definition of `circuit_equiv` so it obeys functional extensionality (i.e. if a circuit `c` matches the behavior of a function `s`, and the spec `s'` produces the same result as `s` for all inputs, then `c` matches the behavior of `s'` as well)
- prove that `circuit_equiv` now obeys functional extensionality
- make the `circuit_spec` tactic use `cbn` instead of `unfold`
Then, kind of unrelatedly, I decided to take a stab at proving that `circuit_equiv` between a circuit and a spec (function) implies that the spec is equivalent to `combinational_evaluation'` of the circuit, which is a proof we eventually need …
> Proofs about circuit_equiv

- cava/cava/Cava/BitArithmetic.v
This PR proves the lemma:
```coq
Lemma list_bits_to_nat_cons b bs :
list_bits_to_nat (b :: bs) = N.b2n b + 2 * list_bits_to_nat bs.
```
which shows how a bit-vector representation of an unsigned binary number can be decomposed into a value from the LSB plus two times the rest of the bit-vector (i.e. shift right by 1). This is useful in proofs that relate bit-vector level arithmetic operations to arithmetic operations at the level of the `N` type or other types like `nat`.
The original proof was done by @jadephilipoom in b7364dc5923cac09dbc1281a1f6099b5b278cc65 and this version adds commentary and a few adjustments to make it easier (at least for me) to follow.
> Proof of list_bits_to_nat_cons

- cava/cava/Cava/Monad/Combinators.v
- cava/cava/Cava/VectorUtils.v
In the course of proving specifications for various arrow combinators, I accumulated a whole bunch of general `Vector.t` proofs. This PR adds those to `VectorUtils.v`. In order to make the proofs easier, I changed some of the custom vector functions (`vreverse`, `vsnoc`, and `vunsnoc`) to recurse on the *length* of the vector, instead of on the vector itself.
The one other change here is that I took `fold_left_S` out of the `vsimpl` set of rewrite hints. The problem is that it triggers any time it sees `fold_left` with a length that matches `S _` -- and `4` is just a notation for `S (S (S (S 0)))`, so if you have a `fold_left` with length 8 it'll apply itself 8 times and make your goal huge. It's still added to the `push_vector_fold` set of hints, so you can get the same behavior as …
> Many, many useful proofs about vectors

- cava/cava/Cava/Arrow/CircuitLowering.v
- cava/cava/Cava/Arrow/CircuitSemantics.v
- cava/cava/Cava/BitArithmetic.v
- cava/cava/Cava/VectorUtils.v
I think I named these, but now I don't think these need to be prefixed. Where there is ambiguity with list functions, the module name could/should be used to differentiate. Also simplifies the traverse definition.
> Remove v prefix from a number of VectorUtils functions

- cava/arrow-examples/Aes/pkg.v
- cava/arrow-examples/Aes/sbox_canright.v
- cava/arrow-examples/CombinatorProperties.v
- cava/arrow-examples/_CoqProject
- cava/cava/Cava/Arrow/CircuitFunctionalEquivalence.v
- cava/cava/Cava/Tactics.v
This PR includes some changes to the `circuit_spec` tactic that use the lemmas in #229 to unfold `closure_conversion'` one constructor at a time, which speeds it up considerably. I then used the sped-up tactic to prove functional equivalence for most of the circuit combinators (I had these proofs lying around already because I needed them for the AES top-level proof I'm working on, but they were due to be separated out and merged and also good test cases!)
> Combinator equivalence proofs

- cava/cava/Cava/Monad/MonadFacts.v
- cava/cava/_CoqProject
This PR ports over some of the proofs about monads that @jadephilipoom wrote in https://github.com/project-oak/oak-hardware/commit/b7364dc5923cac09dbc1281a1f6099b5b278cc65 which I have tried to simplify a bit for my comprehension. I've checked that these definitions allow the ripple-carry adder correctness to still be proved (with minor adaption).
I've added comments that show the goals as they develop. I appreciate this may be poor form? Especially since we can't expect these to be stable from one release of Coq to another?
> Prove facts about identity monad and combinational

- cava/cava/Cava/Spec/Aes.v
- cava/cava/_CoqProject
AES forward cipher and equivalent inverse cipher, based on the [FIPS documentation](https://nvlpubs.nist.gov/nistpubs/FIPS/NIST.FIPS.197.pdf). The equivalent inverse cipher is the version OpenTitan implements. This is about the level of abstraction I need for the top-level AES cipher block in #242.
OpenTitan implements both cipher directions by threading through a boolean argument (`op_i`) that says whether it should do the inverse cipher or not, so a more faithful version would look something like:
```
Definition cipher (op_i : bool) (first_key last_key : key) (middle_keys : list key)
(input : state) : state :=
let st := input in
let st := add_round_key st first_key in
let st := fold_left
(fun (st : state) (round_key : key) =>
let st := sub_bytes op_i st in
let st := shift_rows op_i st …
```
> High-level Gallina AES spec

- cava/cava/Cava/Spec/Aes.v
We should be sure to have license headers on all our source files. Sorry, I should I have mentioned this for the original PR.
> Add license header to AES spec

- cava/opentitan/Makefile
- cava/opentitan/pinmux/Makefile
- cava/opentitan/pinmux/snapshot/Makefile
Add the generation of the Silver Oak to the system build (and pre-submit) and also check the generated SystemVerilog for our pinmux by linting it with Verilator in situ with the dependent SystemVerilog files.
> Add pinmux build to the system build

- cloudbuild.yaml
This will hopefully solve the transient build errors ( #268 ) 
I can't guarantee it as I cannot manually trigger the GCB build difference
> CI: Don't fail if .git exists

- arrow-examples/Aes/CipherProperties.v
- arrow-examples/CombinatorProperties.v
- arrow-examples/_CoqProject
I wasn't getting anywhere on improving arrow performance, so I backtracked a little farther and tested out what happens if I derive the spec from the `kappa` representation instead. With several strategic `Opaque` declarations, the performance issues pretty much disappeared. `CombinatorProperties.v` went down from 26s to 1.4s compilation on my machine, and I was able to derive a spec for `unrolled_cipher_naive'` and typecheck its correctness proof!
One drawback of this change is that now we will need to write a correctness proof for `combinational_evaluation`, which was not required with the previous design. I'll probably start working on that right after this is merged, just to get an early warning if that proof turns out to be complex.
@blaxill now that there's a strategy that works for …
> Derive specifications from Kappa representation

- arrow-examples/Aes/CipherProperties.v
Caused by #269 and #271 being merged at about the same time, so the new file created in #271 had an import that #269 invalidated. This commit removes the bad import (which is now subsumed by `Arrow.ArrowExport`, so no further imports needed to be added).
> Remove outdated import

- arrow-examples/CombinatorProperties.v
- cava/Cava/Arrow/CircuitFunctionalEquivalence.v
- cava/Cava/Arrow/ExprEquiv.v
- cava/Cava/Arrow/ExprLowering.v
- cava/Cava/Arrow/ExprLoweringPreservation.v
- cava/Cava/Arrow/ExprSemantics.v
- cava/Cava/Arrow/ExprSyntax.v
This proof went...much easier than I expected! The punchline is this theorem from `ExprLoweringPreservation.v`:
```
Theorem closure_conversion_preserves_semantics i o (expr : Kappa i o) x :
Wf expr -> NoLetRec expr ->
interp_combinational (expr coq_func) x = combinational_evaluation
(closure_conversion expr) x.
```
The restrictions are that a) the Kappa expression must be `Wf`, meaning that it doesn't change its structure based on the `var` you pass in, and b) that there can't be `LetRec` constructors in the expression (because otherwise it wouldn't be combinational).
Other changes included here are:
- change `var` type to `Kind -> Type` instead of `Kind -> Kind -> Type`. The first (input/source) type was always `Unit`, so the argument provided no useful information or generality, and …
> Proof that closure conversion preserves semantics

- Makefile
- arrow-examples/Aes/netlists.v
- arrow-examples/UnsignedAdder.v
- cava/Cava/Kind.v
- cava/Cava/Monad/CombinationalMonad.v
- cava/Cava/Netlist.v
- cava/Cava/Signal.v
- cava/Cava/Types.v
- cava/Cava2SystemVerilog.hs
- monad-examples/AdderTree.v
- monad-examples/Multiplexers.v
- monad-examples/Sorter.v
- monad-examples/UnsignedAdderExamples.v
- monad-examples/xilinx/XilinxAdderExamples.v
- monad-examples/xilinx/XilinxAdderTree.v
- monad-examples/xilinx/_CoqProject
- silveroak-opentitan/pinmux/Pinmux.v
Rename `BitVec` to `Vec`.
Adresses #276 
In preparation for trying to remove type level vector smahsing.
> Rename BitVec constructor of Kind to Vec

- monad-examples/Makefile
- monad-examples/xilinx/Makefile
- tests/Makefile
- tests/xilinx/.gitignore
- tests/xilinx/Makefile
This fixes the dependencies for the generation of SystemVerilog files, SV testbenches and VCD files that are the result of Verilator simulation. Now `make` can be invoked with any other intermediate targets.
> Fixup Makefile build rules for SystemVerilog generation

- cava/Cava/Arrow/ExprEquiv.v
- cava/Cava/Arrow/ExprLoweringPreservation.v
All `kappa` constructors are now included, which paves the way to proving that the AES cipher implementations are `Wf`.
> Add Let and RemoveContext cases to kappa_equivalence

- arrow-examples/Aes/CipherProperties.v
- arrow-examples/CombinatorProperties.v
This is not yet plugged into proofs, but serves as a sanity check that the circuits follow the preconditions needed to prove that `closure_conversion` preserves semantics (see #273). I'm leaving `Wf` admitted for the same subcircuits that I've left admitted for the equivalence proofs.
> Prove Wf for arrow combinators and unrolled_cipher_naive

- arrow-examples/Aes/OpenTitanCipherProperties.v
- arrow-examples/CombinatorProperties.v
- arrow-examples/_CoqProject
The proofs are analogous to the ones in `NaiveCipherProperties.v`, and are stated in terms of  of the subroutines `cipher_round`, `final_cipher_round`, `mix_columns`, and `key_expand`.
> Prove spec and Wf of unrolled_opentitan_cipher definitions

- arrow-examples/Aes/CipherRoundProperties.v
- arrow-examples/Aes/NaiveCipherProperties.v
- arrow-examples/Aes/OpenTitanCipherProperties.v
- arrow-examples/_CoqProject
This PR proves `Wf` and derives specifications for `cipher_round` and `final_cipher_round`. Then it uses the new proofs instead of assumptions for the final top-level cipher proofs in `NaiveCipherProperties.v` and `OpenTitanCipherProperties.v`. These top-level proofs are now in terms of the standard AES subroutines (`sub_bytes`, `shift_rows`, `mix_columns`, and `key_expand`) instead of in terms of `cipher_round` and `final_cipher_round`, which brings them to the same level of abstraction as the existing AES specification in `silveroak-opentitan`.
> Prove Wf and spec for cipher_round definitions

- cava/Cava/Arrow/CircuitFunctionalEquivalence.v
- cava/Cava/Arrow/CircuitSemantics.v
- cava/Cava/Arrow/DeriveSpec.v
- cava/Cava/Arrow/ExprSemantics.v
- cava/Cava/Arrow/Primitives.v
This reduces duplication and removes the need for `ExprSemantics.v ` to depend on `CircuitSemantics.v `
> Separate primitive semantics

- .gitignore
- cava/Cava/Acorn/Acorn.v
- cava/Cava/Acorn/AcornCavaClass.v
- cava/Cava/Acorn/AcornCombinators.v
- cava/Cava/Acorn/AcornNetlist.v
- cava/Cava/Acorn/AcornNetlistGeneration.v
- cava/Cava/Acorn/AcornSignal.v
- cava/Cava/Acorn/AcornState.v
- cava/Cava/Acorn/Combinational.v
- cava/Cava/Acorn/Lib/AcornFullAdder.v
- cava/Cava/Acorn/Lib/AcornUnsignedAdderProofs.v
- cava/Cava/Acorn/Lib/AcornUnsignedAdders.v
- cava/Cava/Acorn/Tests/UnsignedAdderTests.v
- cava/_CoqProject
This PR introduces an experimental kernel for Cava that is a simplified version of our current monad kernel. I'm calling this kernel "Acorn". Simplifications include dispensing with the shape type and also removing smashing at the type level. The combinator definition of `col` is also simpler than what we currently have in the monad kernel.
The PR includes two lemmas in the file `Cava/Acorn/Lib/AcornUnsignedAdderProofs.v`: one for a list-based adder and one for a vector based adder. Note some useful monad facts are imported. It would be instructive to see:
* Is the list based adder proof any simpler than what happens in https://github.com/project-oak/oak-hardware/pull/218 ? 
* If it is possible to do the equivalent proof for the vector-based adder, then how do they compare? Or can this …
> An experimental simplified monad kernel: Acorn.

- Makefile
Since we have the Coq-proofs-only target in subdirectories, I found it convenient to add a top-level target that calls them all, in case I want to build the arrow-examples coq proofs and am too lazy to type  `make -C cava coq && make -C arrow-examples coq`!
> Add coq target to top-level Makefile

- cava/Cava/Acorn/Lib/AcornUnsignedAdderProofs.v
On top of #287 -- see individual commits for the real diff
Adds proofs for the list- and vector-based adders using the Acorn kernel. Some thoughts:
- The list proof ended up almost exactly the same as with the old kernel. Changes included some slight simplification due to the fact that `colL` is defined directly, while the previous `col` was defined in terms of `below_cons`.
- The vector proof was almost exactly the same as the list proof, but there was some pain involved with resizing vectors (the adder produces a vector of length `n+1`, so the inductive case ends up with a length  `S n + 1` that needs to simplify to `S (n + 1)` to allow the right simplification. And of course a normal rewrite doesn't work because then the types don't line up. I ended up solving this by putting a …
> Acorn adder proofs

- third_party/Makefile
Found a missing underscore! This was causing the `clean` target in `third_party` to error. Shows me to assume I know the bedrock2 targets well enough not to thoroughly test them.
> Fix typo in bedrock2 clean target

- README.md
Users should just have to type:
```console
$ make
```
to build most of the repo (that excludes Xilinx tools specific targets).
Nix is used for CI.
> Remove nix from install instructions

- cava/Cava/Arrow/ExprLowering.v
This might have been the one pointed out previously by @jadephilipoom, but it looks like we didn't fix it yet
> Remove redundant arrow terms

- cava/Cava/Acorn/Lib/AcornUnsignedAdderProofs.v
- cava/Cava/Arrow/CombinatorProperties.v
- cava/Cava/BitArithmetic.v
- cava/Cava/ListUtils.v
- cava/Cava/VectorUtils.v
I have managed to prove that the arrow-based AES implementation, assuming subroutines are correct, matches the top-level spec! :tada: But the punchline will come in a later PR. To get there, I had to do quite a bit of basic standard-library-level lemmas for vectors and lists, which were sizable enough to be their own PR. Changes included here:
- Move some of the proofs about `to_list` from the Acorn adder proofs to `ListUtils` so we can import them easily elsewhere
- Create some new autorewrite databases for list/vector proofs (try the new tactic `length_hammer` on your next annoying list-lengths subgoal!)
- Definition and several proofs about `fold_left_accumulate`, a variant of `fold_left` that accumulates a list of (a projection of) all the states it passed through (this was helpful …
> Helper lemmas about lists, vectors, and denote_kind_eqb

- cava/Cava/ListUtils.v
- silveroak-opentitan/aes/Arrow/OpenTitanCipherEquivalence.v
- silveroak-opentitan/aes/Arrow/_CoqProject
- silveroak-opentitan/aes/Spec/Cipher.v
- silveroak-opentitan/aes/Spec/ExpandAllKeys.v
- silveroak-opentitan/aes/Spec/InterleavedCipher.v
- silveroak-opentitan/aes/Spec/_CoqProject
Resolves the cliffhanger I teased in #298! I first defined an alternative spec-level implementation that has key-generation interleaved, and then proved that equivalent to the original spec. Then, I proved that the derived top-level behavior of the `unrolled_opentitan_cipher` matches the alternative version.
There are a few oddities I'd like to address that came up while doing the proof; I've marked them as TODOs in the code.
1. The implementation transposes the key before performing `add_round_key`. Why?
2. It looks like the implementation does 15 rounds instead of 14 -- or am I misreading the FIPS spec?
3. The starting key pair seems to be reversed.
This PR completes phase 1 of the AES verification plan! :tada: :tada: :tada:
> Proof that arrow-based AES top-level spec and FIPS-based spec are equivalent

- arrow-examples/Counter.v
- arrow-examples/Fir.v
- cava/Cava/Arrow/ArrowKind.v
- cava/Cava/Arrow/CircuitArrow.v
- cava/Cava/Arrow/CircuitFunctionalEquivalence.v
- cava/Cava/Arrow/CircuitLowering.v
- cava/Cava/Arrow/CircuitProp.v
- cava/Cava/Arrow/CircuitSemantics.v
- cava/Cava/Arrow/ExprLowering.v
Also leave `rewrite_or_default` to arrow interpreter, rather than performing `rewrite_or_default` as a construction of arrow constructors.
Fixes #301
> Use 'circuit_evaluation' to generate the sequential tb outputs

- silveroak-opentitan/aes/Arrow/OpenTitanCipherEquivalence.v
This follows up on a discussion with @blaxill and resolves the two remaining TODOs I left on #299 to make sure that the top-level proof really says what we want it to say. The OpenTitan implementation operates with keys in transposed form, so we have to transpose the keys back before passing them to the human-written spec. Luckily the structure used for projecting out only one of paired keys is general enough to be reused, so this ended up being a very minimal change. I also updated the comment about the reversal of the first key to explain why it's reversed instead of ask why.
> Resolve TODOs on top-level proof

- cava/Cava/Acorn/AcornCavaClass.v
- cava/Cava/Acorn/AcornCombinators.v
- cava/Cava/Acorn/AcornNetlistGeneration.v
- cava/Cava/Acorn/Combinational.v
- cava/Cava/Acorn/Lib/AcornFullAdder.v
- cava/Cava/Acorn/Lib/AcornUnsignedAdders.v
- cava/Cava/Acorn/Lib/AcornVectors.v
- silveroak-opentitan/aes/Acorn/CipherRound.v
This removes `m` as a typeclass variable and makes it a member instead. This simplifies the type context for Acorn circuits.
Addresses #318
> Remove m as typeclass variable

- cava/Cava/Acorn/AcornCombinators.v
- cava/Cava/Acorn/AcornSignal.v
- cava/Cava/Acorn/Combinational.v
- silveroak-opentitan/aes/Acorn/CipherEquivalence.v
- silveroak-opentitan/aes/Acorn/CipherRound.v
- silveroak-opentitan/aes/Acorn/_CoqProject
Resolves #315 
This proof was very easy! Probably had a lot to do with the fact that the implementation was based on the spec. A good follow-up to this would be to create an Acorn-based AES implementation that's closer to OpenTitan, and see how we do with that.
Also included in this PR is a typo fix and a couple of proofs about the new `foldLM` definition -- only one is currently used, but the other might be useful later.
> Acorn-based AES equivalence

- Makefile
- arrow-examples/Makefile
- monad-examples/Makefile
- monad-examples/xilinx/Makefile
- silveroak-opentitan/Makefile
- silveroak-opentitan/aes/Acorn/Makefile
- silveroak-opentitan/aes/Arrow/Makefile
- silveroak-opentitan/aes/Makefile
- silveroak-opentitan/aes/Spec/Makefile
- silveroak-opentitan/pinmux/Makefile
- tests/Makefile
- tests/xilinx/Makefile
- third_party/Makefile
I wanted to get rid of some of the repetitive code in our Makefiles. In particular, we have a lot of sub-makes, and logic was repeated for every subdirectory. I also wanted to make the Makefiles a little more uniform. This PR:
- Inserts a `SUBDIRS` variable in each Makefile with sub-makes that contains all the subdirectories, and makes all the logic dependent on that variable. Now, to add a subdirectory, you don't need to go through and copy code in several targets; you need only to add its name to `SUBDIRS` and, if it has dependencies on other subdirectories, add a `foo: bar` target to declare `bar` should be built before `foo`.
- Adds `.vo` targets to every Makefile, including the higher-level ones; you can now call `make cava/Cava/Acorn/AcornCombinators.vo` on the top-level directory …
> Clean up logic in Makefiles

- cava/Cava/Arrow/CavaNotation.v
- cava/Cava/Arrow/CircuitArrow.v
- cava/Cava/Arrow/CircuitFunctionalEquivalence.v
- cava/Cava/Arrow/CircuitLowering.v
- cava/Cava/Arrow/CircuitProp.v
- cava/Cava/Arrow/CircuitSemantics.v
- cava/Cava/Arrow/Classes/Arrow.v
- cava/Cava/Arrow/Classes/Category.v
- cava/Cava/Arrow/CombinatorProperties.v
- cava/Cava/Arrow/DeriveSpec.v
- cava/Cava/Arrow/ExprEquiv.v
- cava/Cava/Arrow/ExprLowering.v
- cava/Cava/Arrow/ExprSemantics.v
- cava/Cava/Arrow/ExprSyntax.v
- cava/Cava/Arrow/Primitives.v
- silveroak-opentitan/aes/Arrow/_CoqProject
- silveroak-opentitan/aes/Arrow/pkg.v
Reverts project-oak/oak-hardware#314
- Reverting since this change broke some proofs that CI missed
> Temporarily Revert "Cleanup primitive structures"

- cava/Cava/ListUtils.v
- silveroak-opentitan/aes/Arrow/OpenTitanCipherEquivalence.v
- silveroak-opentitan/aes/Spec/CipherRepresentationChange.v
- silveroak-opentitan/aes/Spec/ExpandAllKeys.v
- silveroak-opentitan/aes/Spec/InterleavedCipher.v
- silveroak-opentitan/aes/Spec/_CoqProject
Reduces the complexity of the definitions and proofs in `silveroak-opentitan/aes/Spec/InterleavedCipher.v`, which defines a version of the top-level AES cipher that interleaves key expansion with cipher rounds and proves that it's equivalent to the version with keys precomputed (`Cipher.v`). The key trick here is a generic proof about changing the representation of keys in the top-level spec.
Previously, we proved that the interleaved version was equivalent to the precomputed-keys version _defined over a different key type_, which was necessary because the existing AES implementation operates on pairs of keys instead of single keys. That introduced a lot of extra boilerplate like a different definition of `add_round_key` for each key type. With a generic key-representation change lemma, …
> Clean up key-expansion-interleaving proofs

- silveroak-opentitan/aes/Spec/AddRoundKey.v
- silveroak-opentitan/aes/Spec/_CoqProject
This uses Vector.t to implement state and key, and it adds a
definition of add_round_key and proves it is its own inverse.
- suggestions for using VectorUtils.v appreciated (export vnil?)
- Adding nc/nb to context instead of making them dependently typed was causing some issues in my proofs where
it couldn't match 'nc' and 'nc0' with each other.
> Cipher.v: state/key/add_round_key

- cava/Cava/ListUtils.v
- silveroak-opentitan/aes/Spec/Cipher.v
- silveroak-opentitan/aes/Spec/ExpandAllKeys.v
- silveroak-opentitan/aes/Spec/InterleavedCipher.v
- silveroak-opentitan/aes/Spec/InterleavedInverseCipher.v
- silveroak-opentitan/aes/Spec/_CoqProject
This is progress towards #334 ; the proof that the AES inverse cipher implementation matches the main spec (which uses precomputed keys) will be done by proving that the implementation matches this interleaved version, and then using the proof that the interleaved version is equivalent to the precomputed-keys version.
Includes:
- Version of the equivalent inverse cipher with key expansion interleaved with cipher rounds
- Proof that this definition is equivalent to the original spec with precomputed keys (the proof actually is in terms of the keys from the forward direction)
- Improvements/more lemmas added to `fold_left_accumulate` section in `ListUtils.v`
The proof of equivalence with the precomputed-keys is a bit more complex than it was for the forward direction, primarily because, …
> Interleaved inverse cipher spec

- cava/Cava/VectorUtils.v
- silveroak-opentitan/aes/Arrow/OpenTitanCipherEquivalence.v
- silveroak-opentitan/aes/Arrow/PkgProperties.v
This is also progress towards #334 
I had to prove several sublemmas for this about custom vector definitions like `snoc`/`unsnoc`, and I had to move a few existing proofs earlier in the file so I could put, for instance, `map2` sublemmas with other sublemmas about `map2`.
> Move transpose_rev to VectorUtils and prove it is involutive

- silveroak-opentitan/aes/Spec/AddRoundKey.v
Lines these up with the standard, also renames key to
key_schedule_round, since this is actually a round-specific piece of the
key schedule.
> AddRoundKey: clarify variable names

- silveroak-opentitan/aes/Spec/AddRoundKey.v
I was trying to prove equivalence of the Acorn-based add-round-key with the spec, and realized that there was a minor error; the spec was xor-ing each word of the state with a one-word key, while it should be xor-ing *corresponding* words from the state and an `nb`-word key. The change is very small, so kudos to @smore-lore for a nice and flexible design!
Definitely a point in favor of #344
> Make add_round_key use `nb`-word key

- cava/Cava/Arrow/CombinatorProperties.v
- silveroak-opentitan/aes/Arrow/CipherEquivalenceCommon.v
- silveroak-opentitan/aes/Arrow/OpenTitanCipherEquivalence.v
- silveroak-opentitan/aes/Arrow/OpenTitanInverseCipherEquivalence.v
- silveroak-opentitan/aes/Arrow/_CoqProject
- silveroak-opentitan/aes/Spec/CipherRepresentationChange.v
- silveroak-opentitan/aes/Spec/ExpandAllKeys.v
- silveroak-opentitan/aes/Spec/InterleavedCipher.v
- silveroak-opentitan/aes/Spec/InterleavedInverseCipher.v
Resolves the arrow-based part of #334 
- **Proof that the arrow-based inverse cipher implementation matches the inverse cipher spec**
- A few additional proofs about arrow combinators that I needed to do the proof
- Refactoring of some common structures from forward/inverse equivalence proofs into a separate, mutually imported file
- Extra lemmas about `all_keys` that aren't currently used but might be helpful in the future
I was really spinning my wheels on this one for a while, mostly because I was trying to write the equivalence proof by only providing an expression for the full list of forward keys, and then writing the precomputed keys for the inverse function as the reverse of this list. However, that makes the proof much trickier, because on top of reasoning about the equivalence …
> Inverse cipher equivalence (arrow-based)

- cava/Cava/Acorn/Identity.v
- cava/Cava/VectorUtils.v
- cava/_CoqProject
- silveroak-opentitan/aes/Acorn/AddRoundKey.v
- silveroak-opentitan/aes/Acorn/AddRoundKeyEquivalence.v
- silveroak-opentitan/aes/Acorn/CipherEquivalence.v
- silveroak-opentitan/aes/Acorn/CipherRound.v
- silveroak-opentitan/aes/Acorn/Common.v
- silveroak-opentitan/aes/Acorn/_CoqProject
Before doing the Acorn-based inverse cipher equivalence proof for #334, I did some cleanup of the forward proof. I separated out the add-round-key/xor part, and used our brand-new add-round-key spec to prove equivalence for that part of the cipher.
> Acorn add round key equivalence

- silveroak-opentitan/aes/Acorn/CipherEquivalence.v
Last piece; finally resolves #334 
Because we're using the equivalent inverse cipher, which has all the subroutines in the same order, I didn't even need to make a different definition; if you assume the subroutine context variables are in fact the inverse operations, then you get the inverse cipher. (I could have done this with the top-level spec as well, but thought that in that case it was best to have two separate definitions for readability.)
> Inverse cipher equivalence (acorn-based)

- cava/Cava/Monad/CavaClass.v
- cava/Cava/Monad/CombinationalMonad.v
- cava/Cava/Monad/NetlistGeneration.v
- cava/Cava/Netlist.v
- cava/Cava/Signal.v
- silveroak-opentitan/pinmux/Pinmux.v
Needed for blackBox module instantiation to become an overloaded operation, with the combinational and sequential instantiations yielding default values for the behaviour of an unspecified external block (as currently used in the pinmux).
> Add generation of interface tuple default values

- cava/Cava/Arrow/CavaNotation.v
- cava/Cava/Arrow/Combinators.v
- silveroak-opentitan/.gitignore
- silveroak-opentitan/aes/Arrow/cipher_core.v
- silveroak-opentitan/aes/Arrow/cipher_round.v
- silveroak-opentitan/aes/Arrow/key_expand.v
- silveroak-opentitan/aes/Arrow/shift_rows.v
~~Requires #341 or similar changes before this will pass CI~~
This is the `aes_cipher_core` to be a drop in for the OpenTitan version. There are a few outstanding items I will track in #357
> OpenTitan aes_cipher_core replacement

- tests/Delay.v
Progress on #371 
With a minor modification (using a bitvector as the state instead of an `N`), and depending on an admitted proof that `addN` is correct, I was able to take the counter and spec in #367 and prove that they correspond. I put in a little automation as well -- review commit-by-commit to see the proofs before I sprinkled tactic magic on them.
Next step is to prove the admitted `addN` lemma, but I thought it was worth getting feedback on this step first.
> Count by proofs

- tests/CountBy/CountBy.v
- tests/CountBy/ListProofs.v
- tests/CountBy/VectorProofs.v
- tests/Delay.v
- tests/_CoqProject
Progress for #371
Related to #374 
Proofs of `countBy` using the vector-based sequential semantics. The first two commits are just reorganizing; I moved the `countBy` example out of `Delay.v` and into its own file, and created a directory for all the `countBy` files since I anticipate we'll have a few more tests as well. So the only commit needing review is the third and final one, which adds `tests/CountBy/VectorProofs.v`.
The proof worked out pretty easily. The vector representation does trip up the proof automation a little bit, so I have to sometimes explicitly pass in the number of ticks to rewrites. But I think we can work around that, and all in all I was able to reuse most of the automation from lists, which I think is a good sign.
> Vector counter

- cava/Cava/Monad/CavaClass.v
- cava/Cava/Monad/CombinationalMonad.v
- cava/Cava/Monad/NetlistGeneration.v
- cava/Cava/Monad/Sequential.v
- cava/Cava/Monad/SequentialV.v
- monad-examples/NandGate.v
- tests/CountBy/CountBy.v
- tests/CountBy/ListProofs.v
- tests/CountBy/VectorProofs.v
- tests/Delay.v
Following up on discussion with Satnam (and my own ambitions to do more sequential representation experiments), this PR makes the sequential Cava semantics into a class that "extends" the combinational one.
We had previously discussed putting the combinational semantics inside the class as a field, i.e.
```coq
Class CavaSeq signal :=
{ combinationalSemanatics :> Cava signal;
....
}
```
However, I ran into two problems with that approach in contexts that looked like:
```
Context {signal} {semantics : Sequential signal}.
```
The first problem was that typeclass inference wanted to plug in every concrete instance it could possibly find before trying `(combinationalSemantics semantics)`. Since there are several such instances exported by `CavaMonad`, it was picking up all of those. However, I …
> Cava class hierarchy

- cava/Cava/Monad/Sequential.v
- tests/AddWithDelay/AddWithDelay.v
- tests/CountBy/ListProofs.v
- tests/_CoqProject
I think (although not thoroughly tested by any means) I have figured out how to run sequential subcircuits inside of loops for the list-based representation. The key here is the observation that, because delays are represented in the value list, running the loop body on a single input gives me the values on the feedback wire from t=1 onward (1 because of the loop-feedback delay). If there are already values queued on the feedback wire, then my circuit is malformed if it produces anything but delays in those cases -- I can safely overwrite them with the values I already have.
The operation `overlap` performs this chaining of loop step outputs. I've added a test (no proofs yet) that is pretty much `countBy` but with an extra delay inserted inside the loop body.
What do people think of this …
> Loop with sequential subcircuit

- _CoqProject
- cava/Cava/Acorn/Identity.v
- cava/Cava/Lib/UnsignedAdders.v
- cava/Cava/Monad/Combinators.v
- cava/Cava/Monad/Sequential.v
- cava/Cava/Monad/SequentialV.v
- monad-examples/UnsignedAdderExamples.v
- tests/AddWithDelay/AddWithDelay.v
- tests/CountBy/CountBy.v
- tests/CountBy/ListProofs.v
- tests/CountBy/TimedProofs.v
- tests/CountBy/VectorProofs.v
- tests/Delay.v
This PR attempts to change the type of `addN` to take a pair rather than be a curried function, which lets me write `countBy` the way I want to:
```coq
Definition countBy : signal (Vec Bit 8) -> cava (signal (Vec Bit 8))
:= loop (addN >=> fork2).
```
However, I run into trouble when I try to adapt the List proof. Specifically at:
```coq
Lemma countForkCorrect:
forall (i : list (Bvector 8)) (s : Bvector 8),
sequential (loopSeq' (addN >=> fork2) i [s])
= countBySpec' s i.
```
Before the `sequential` line was:
```coq
sequential (loopSeq' (countFork (combsemantics:=SequentialCombSemantics)) i [s])
```
which seems to use an annotation to make sure the `countFork` function is interpreted in the `ident` monad.
I can't work out how to write the equivalent thing for `addN >=> fork2` and currently …
>  Change addN to take a pair for better use in combinators

- cava/Cava/ListUtils.v
- silveroak-opentitan/aes/Spec/AddRoundKey.v
- silveroak-opentitan/aes/Spec/CipherRepresentationChange.v
- silveroak-opentitan/aes/Spec/CommuteProperties.v
- silveroak-opentitan/aes/Spec/Placeholder/MixColumns.v
- silveroak-opentitan/aes/Spec/Sbox.v
- silveroak-opentitan/aes/Spec/ShiftRows.v
- silveroak-opentitan/aes/Spec/SubBytes.v
- silveroak-opentitan/aes/Spec/Tests/CipherTest.v
- silveroak-opentitan/aes/Spec/_CoqProject
Please leave suggestion for how to name 'CommuteProperties.v'. I'm not sure on this, but was imagining we'd have the mix columns/sub bytes commutativity property there as well.
closes #310
> shift_rows/sub_bytes commutivity

- cava/Cava/Acorn/Sequential.v
- cava/Cava/Acorn/SequentialProperties.v
- cava/Cava/Lib/UnsignedAdders.v
- cava/Cava/ListUtils.v
- cava/Cava/VectorUtils.v
- tests/AddWithDelay/AddWithDelay.v
- tests/AddWithDelay/ListProofs.v
- tests/CountBy/ListProofs.v
- tests/CountBy/TimedProofs.v
- tests/CountBy/VectorProofs.v
- tests/_CoqProject
Resolves #387 
Related: #371
I ended up using a pretty non-mechanical specification after all, which follows the function-from-nat model of sequential semantics similar to the timed monad. It was just the most natural way (for me) to encode what this contrived circuit is doing. Nonetheless, the proof went through just fine, although with more list-manipulation reasoning. I've been gradually improving our automation for list proofs, so if we end up wanting to go this direction the proofs should get less annoying over time.
> Proofs for add-with-delay

- tests/SignallingCounter/SignallingCounter.v
- tests/_CoqProject
Progress on #376 
This adds the implementation (no proof yet) of a signalling counter that takes in a valid bit to determine whether it accepts an input. One awkwardness I noticed is that the current loop structure locks us into only one input and one feedback signal for the loop, so in order to take both a valid bit and an 8-bit counter input for each iteration I had to concatenate them into a 9-bit vector. I think we can probably do better; I'll think about it and make an issue so we remember to discuss it once the holidays are over.
> Add signalling counter example

- cava/Cava/Acorn/CavaClass.v
- cava/Cava/Acorn/Combinators.v
- cava/Cava/Acorn/NetlistGeneration.v
- cava/Cava/Acorn/Sequential.v
- cava/Cava/Acorn/SequentialV.v
- tests/SignallingCounter/SignallingCounter.v
This PR is a work in progress that attempts to add new loop combinators that expose the current state value directly at the output.
See  #371 for details.
The current formulation is wrong as illustrated by the failed `Example` in `SignallingCounter.v":
```coq
Compute map Bv2N (sequential (counterWithEnableTop
(combine
(# [1;1;1;1;1;1;1;1])
(map nat2bool [1;1;1;1;0;0;0;0])))).
```
which gives:
```coq
= [4%N]
: list N
```
i.e. only the last value in the current state stream. I think this is because I've made a wrong guess about how to adapt `loopSeq` to also expose the state stream:
```coq
Definition loopSeqS {A B C : SignalType}
(f : seqType A * seqType C -> ident (seqType B * seqType C))
(a : seqType A) : ident (seqType B * seqType C) :=
snd (fold_left (loopSeq' f) a (0, ret ([], …
```
> Add loopDelayS and loopDelaySEnable for state output

- cava/Cava/Acorn/CombinationalProperties.v
- cava/Cava/Acorn/Combinators.v
- cava/Cava/Acorn/Identity.v
- cava/Cava/BitArithmetic.v
- cava/Cava/ListUtils.v
- cava/Cava/NatUtils.v
- cava/Cava/Tactics.v
- cava/Cava/VectorUtils.v
- silveroak-opentitan/aes/Arrow/OpenTitanCipherEquivalence.v
- silveroak-opentitan/aes/Arrow/OpenTitanInverseCipherEquivalence.v
Progress on #394 
Our current Acorn AES cipher is based on the spec and uses precomputed keys. This PR is part 1 of 2 in changing that design to one that mirrors OpenTitan more closely. In particular, the new version will:
- expand keys on-the-fly by routing through a key expansion circuit (nonexistent, for now)
-  operate more like a state machine; more details in the next PR.
I've separated out all the general-purpose infrastructure (i.e. the changes to `cava`) required fro the change into this "part 1" PR. It's kind of a random mix, but some of the highlights include:
- new tactics - these might be useful for others to take a look at for future proofs!
-  `subst_lets` (inlines all hypotheses bound with `:=`)
- `compute_expr` (replaces a particular subexpression with the computed …
> Groundwork for more OpenTitan-like Acorn cipher

- silveroak-opentitan/aes/Acorn/AES256Equivalence.v
- silveroak-opentitan/aes/Acorn/CipherEquivalence.v
- silveroak-opentitan/aes/Acorn/CipherRound.v
- silveroak-opentitan/aes/Acorn/FullCipherEquiv_Assumptions.out
- silveroak-opentitan/aes/Acorn/FullCipherInverse_Assumptions.out
- silveroak-opentitan/aes/Spec/ExpandAllKeys.v
Resolves #394 
Part 2 of 2 (Part 1 was #410)
There are two main changes in this PR that serve to make the Acorn AES implementation more similar to OpenTitan:
1. We now assume a key expansion circuit exists and call it on-the-fly to generate round keys.
2. The top-level cipher is now defined in terms of `cipher_step`, which given a round index and the current state performs one step of AES (including setting selectors based on the round index and then using them with muxes to choose the right data path).
Most of the changes are modifying the proofs to match the new structure. They're now a longer and more complicated-looking because of bookkeeping deal with the fact that the spec needs precomputed keys (previously, since the spec and the combinational interpretation of the circuit were …
> More OpenTitan-like Acorn cipher

- tests/AccumulatingAdderEnable/AccumulatingAdderEnable.v
- tests/AccumulatingAdderEnable/ListProofs.v
- tests/TestsExtraction.v
- tests/TestsSV.hs
Rename the "signalling counter" to reflect the fact that is is an accumulating adder with a clock-enable input.
> Rename signalling counter to more accurate name

- cava/Cava/Acorn/CavaClass.v
- cava/Cava/Acorn/CombinationalMonad.v
- cava/Cava/Acorn/Combinators.v
- cava/Cava/Acorn/NetlistGeneration.v
- cava/Cava/Acorn/Sequential.v
- cava/Cava/Acorn/SequentialProperties.v
- cava/Cava/Acorn/SequentialV.v
- cava/Cava/ListUtils.v
- tests/AccumulatingAdderEnable/AccumulatingAdderEnable.v
- tests/AccumulatingAdderEnable/ListProofs.v
- tests/AddWithDelay/AddWithDelay.v
- tests/AddWithDelay/ListProofs.v
- tests/CountBy/CountBy.v
- tests/CountBy/ListProofs.v
- tests/CountBy/VectorProofs.v
Resolves a TODO in `CavaClass.v`. The story here is that we initially defined `loopDelay`, a loop whose body has separate output and feedback results; the body's signature is something like like `A * C -> B * C`. We later added `loopDelayS`, which assumes the output and feedback are the same and expects a body with the form `A * B -> B`. There was a TODO to remove `loopDelay` from the typeclass and simply define it in terms of `loopDelayS`, which is what this PR does.
There is a significant proof component here because we had written invariant infrastructure for `loopDelay`, so I redid these proofs for `loopDelayS` instead and then used them to re-prove the top-level invariant proofs for `loopDelay`. Since the existing examples in `tests/` do in fact use the same thing for feedback and …
> Use loopDelayS as the primary loop definition

- cava/Cava/Acorn/CavaClass.v
- cava/Cava/Acorn/CombinationalMonad.v
- cava/Cava/Acorn/Combinators.v
- cava/Cava/Acorn/Sequential.v
- cava/Cava/Acorn/SequentialTimed.v
- cava/Cava/Acorn/SequentialV.v
- cava/Cava/BitArithmetic.v
- cava/Cava/ListUtils.v
- cava/Cava/VectorUtils.v
- tests/CountBy/TimedProofs.v
Part 1 of 2
Progress towards #422 
- Make `SequentialV` and `SequentialTimed` independent of `CombinationalMonad`
- move some bit-arithmetic definitions from `CombinationalMonad` to `BitArithmetic`
- update the timed monad to use `loopDelayS`
- New definition `extend` and a few proofs in `ListUtils`
- New definitions `InV` and `ForallV` in `VectorUtils`[0]
- Generalization of `VectorUtils` lemmas about "algebraic" loops with identity elements and group-like operations
- Generalization of `tree` lemmas to accept validity preconditions on algebraic elements
- Miscellaneous useful helper lemmas about vectors
I've now completed the task set out in #422, but the change is very large, so I've separated out some changes that are required for that change but still build when separated from it …
> Groundwork for consolidating combinational semantics

- cava/Cava/Acorn/CavaClass.v
- cava/Cava/Acorn/CombinationalMonad.v
- cava/Cava/Acorn/NetlistGeneration.v
- cava/Cava/Acorn/Sequential.v
- cava/Cava/Acorn/SequentialTimed.v
- cava/Cava/Acorn/SequentialV.v
- cava/Cava/Acorn/XilinxAdder.v
- cava/Cava/Lib/UnsignedAdders.v
Address #432 
Adds a `constant` member to Cava class to map `bool` values to values denoted via `SignalType`.
> Define a constant member to map bool values to SignalType values

- acorn-examples/Makefile
- acorn-examples/xilinx/Makefile
- acorn-examples/xilinx/XilinxAdderTree.v
- cava/Cava/Acorn/NetlistGeneration.v
- cava/Cava2SystemVerilog.hs
- tests/Makefile
- tests/xilinx/Makefile
Addresses part of  #440
This adjusts the Makefiles for SystemVerilog test generation to correctly handle the generated C++ files as part of the Verilator compile chain. This PR also fixes a mistake in the netlist generation for the new `constant` Cava class method.
> Fix SystemVerilog test execution

- silveroak-opentitan/aes/Acorn/AES256Equivalence.v
- silveroak-opentitan/aes/Acorn/AddRoundKey.v
- silveroak-opentitan/aes/Acorn/AddRoundKeyEquivalence.v
- silveroak-opentitan/aes/Acorn/FullCipherInverse_Assumptions.out
- silveroak-opentitan/aes/Spec/AES256.v
- silveroak-opentitan/aes/Spec/AES256_Assumptions.out
- silveroak-opentitan/aes/Spec/StateTypeConversions.v
- silveroak-opentitan/aes/Spec/Tests/CipherTest.v
Thanks to @smore-lore for flagging this one!
There's a conflict between Coq and FIPS in terms of endianness: Coq (and Cava, by extension) expects little-endian bit vectors, and FIPS is all big-endian. Previously, the conversions in `StateTypeConversions` handled this by taking a little-endian flat bitvector and turning it into big-endian rows and columns, which was most convenient for working with the FIPS-based subroutine specifications. However, some of the type conversions are meant for _implementations_, which will use Cava/Coq and therefore are best left little-endian.
The `cols_bits` and `cols_bitvecs` representationsare used almost exclusively in implementation rather than specification (`add_round_key` uses this representation in specification, but since it's just an xor it …
> Make some AES state representations little-endian

- acorn-examples/MuxExamples.v
- cava/Cava/Acorn/Acorn.v
- cava/Cava/Acorn/CavaPrelude.v
- cava/Cava/Acorn/Combinators.v
- cava/Cava/Acorn/Sequential.v
- cava/Cava/Extraction.v
- cava/Cava2HDL.cabal
I had to move `mux2` from `Lib.Multiplexers` to a prelude file since it is now used "in the core".
Also rename `mux2` to `muxPair` which more accurately reflects what it is doing.
#450
> Remove now redundant mux2 from Combinators

- cava/Cava/Lib/BitVectorOps.v
- silveroak-opentitan/aes/Acorn/MixColumns.v
- silveroak-opentitan/aes/Acorn/Pkg.v
There was a definition for a bit-wise-XOR in `Pkg.v` but we have one in the library `Cava.Lib.BitVectorOps`.
Delete the duplicate definition but also provide a curried version of it `xorv`.
At the same time change one of the vector literals which is constructed by consing into a single Vector literal like `[..; ..; ..]`.
CC: @blaxill
> Remove duplicate bitwise-XOR from Pkg.v

- cava/Cava/Signal.v
- tests/MuxTests.v
With the new combinational simulation semantics we can test combinational circuits with a single `Example` test that works over a stream of values, with each value representing a test vector. Before we had to create separate `Example`s. This PR updates `MuxTest` to remove the single-shot tests and have just one `Example` test. It defines a helper function to map a list of tuples (convenient for cycle by cycle representation of test vectors) to a tuple of lists (which is what the Coq simulation semantics expects). Note question about why I need to explicitly give the `list SignalType` argument to `fromListOfTuples` in `MuxTest.v`: I had guessed this could have been left implicit and inferred from context.
CC: @blaxill
> Simplify mux test

- acorn-examples/Sorter.v
- acorn-examples/UnsignedAdderExamples.v
- cava/Cava/Acorn/CavaClass.v
- cava/Cava/Acorn/CombinationalMonad.v
- cava/Cava/Acorn/NetlistGeneration.v
- cava/Cava/Acorn/SequentialTimed.v
- cava/Cava/Acorn/SequentialV.v
- cava/Cava/BitArithmetic.v
- cava/Cava/Lib/UnsignedAdders.v
- cava/Cava/Netlist.v
- cava/Cava/Signal.v
- cava/Cava2SystemVerilog.hs
- tests/TestMultiply.v
I think it is much better to have the synthesizable arithmetic operations as expressions rather than instantiated circuits. Their types have also been changed to work over tuples to make them easier to use in point-free style (except when specializing on one input in which case the original curried version would have been better).
> Make synthsizable arithmetic operations expressions, not circuits

- cava/Cava2HDL.cabal
- cava/Cava2SystemVerilog.hs
- silveroak-opentitan/aes/Acorn/.gitignore
- silveroak-opentitan/aes/Acorn/AESExtraction.v
- silveroak-opentitan/aes/Acorn/AESSV.hs
- silveroak-opentitan/aes/Acorn/Makefile
- silveroak-opentitan/aes/Acorn/MixColumns.v
- silveroak-opentitan/aes/Acorn/README.md
- silveroak-opentitan/aes/Acorn/verilator.vlt
This PR illustrates sets up SystemVerilog extraction for `aes_mix_columns` but right now it only uses an empty test bench to just check that this block is compiles and is legal SystemVerilog and that it can be processed by Verilator.
Part of addressing issue #458
> Set up SystemVerilog extraction and simulation for aes_mix_columns

- silveroak-opentitan/aes/Acorn/AES256Equivalence.v
- silveroak-opentitan/aes/Acorn/SubBytes.v
For now, porting over LUT-based implementation from sub bytes.
Still working on here - 'reflexivity' proofs in AES256Equivalence.v hang.
Closes #320
> Acorn SubBytes: definition + test

- silveroak-opentitan/aes/Acorn/MixColumnsCircuit.v
- silveroak-opentitan/aes/Acorn/MixColumnsTests.v
There was an indexing typo in mix_columns which only surfaces in the inverse mode. Also added a `aes_test_decrypt` check for inverse mode.
> Fix mix_columns inverse error

- cava/Cava2SystemVerilog.hs
- cava/SystemVerilogUtils.hs
This PR makes the implementation of pair selection work by translation into vector-indexing. This means we no longer need to emit conditional expressions in the generated SystemVerilog. Pair selection can now be defined in a library or prelude module, once the proofs can be adapted.
> Implement pair selection in terms of array indexing

- cava/Cava/BitArithmetic.v
- cava/Cava/ListUtils.v
- cava/Cava/VectorUtils.v
- silveroak-opentitan/aes/Acorn/FullCipherInverse_Assumptions.out
- silveroak-opentitan/aes/Spec/AES256.v
- silveroak-opentitan/aes/Spec/AES256_Assumptions.out
- silveroak-opentitan/aes/Spec/MixColumns.v
- silveroak-opentitan/aes/Spec/Polynomial.v
- silveroak-opentitan/aes/Spec/PolynomialProperties.v
Resolves #295 
This PR fills in the last two admits that were left in #504, which stated that _modular_ multiplication in the AES byte field was associative and distributive.
The strategy here is very computational; after investigating a bit and determining that proving the properties we needed in full generality (i.e. for all polynomials) would likely be very time-consuming, I took advantage of the fact that the AES field has a fixed modulus to write explicit expressions in terms of the input for modular reduction, multiplication, and addition in terms of GF(2) (bit) operations, and then used Coq's `ring` tactic to prove these equivalent.
Because of the computational strategy (which results in pretty large expressions), the proofs are unfortunately pretty slow. Compiling `MixColumns.v` …
> Full proofs of inverse_mix_columns

- silveroak-opentitan/aes/Acorn/.gitignore
- silveroak-opentitan/aes/Acorn/Makefile
- silveroak-opentitan/aes/Acorn/README.md
- silveroak-opentitan/aes/Acorn/aes_sub_bytes.tcl
This PR contains a tcl file for driving the FPGA implementation of the Silver Oak `aes_sub_bytes` block and a rule `impl` that invokes the Xilinx Vivado tool to run the implementation to produce utilization reports (but not bitstream generation). There is no clean to clean the generated output directory because we should be careful about wiping it since it will in general contain artifacts that took a long time to generate.
The comparison with the OpenTitan `aes_sub_bytes` block shows identical utilization.
Part of issue #466
> FPGA implementation of Silver Oak aes_sub_bytes

- silveroak-opentitan/aes/Acorn/FullCipherInverse_Assumptions.out
- silveroak-opentitan/aes/Spec/AES256.v
- silveroak-opentitan/aes/Spec/AES256_Assumptions.out
- silveroak-opentitan/aes/Spec/CommuteProperties.v
- silveroak-opentitan/aes/Spec/MixColumns.v
Resolves #312 
With this PR, we are **completely done** with the proofs on top of the AES specification (i.e. the proofs that decryption is the inverse of encryption). The only proofs now remaining for the top-level theorems are proofs that the Cava implementations match the specification.
The diff is a bit confused because I de-indented the proofs that `shift_rows` and `sub_bytes` commute -- I didn't actually change any of the code there.
> Prove that inv_mix_columns and add_round_key commute

- silveroak-opentitan/aes/Acorn/AES256Equivalence.v
- silveroak-opentitan/aes/Acorn/FullCipherEquiv_Assumptions.out
- silveroak-opentitan/aes/Acorn/FullCipherInverse_Assumptions.out
Resolves #497 
Instead of `first`, trying every side-condition solving strategy in turn, use a `lazymatch` to more specifically try certain strategies on certain goals. This fixes the proof-slowness issue that prevented us from removing the `sub_bytes` axiom before.
> Fix slowness in equivalence proofs

- silveroak-opentitan/aes/Acorn/.gitignore
- silveroak-opentitan/aes/Acorn/Makefile
- silveroak-opentitan/aes/Acorn/README.md
- silveroak-opentitan/aes/Acorn/aes_util.tcl
The updated report with the fix Silver Oak `aes_mix_columns` report shows that we are 4% larger which is not bad. I could investigate to see where this 4% comes from, but I think anything less than 5% is probably not worth worrying about too much.
PR includes documentation to show how to re-generate the reports using the `Makefile`.
Part of issue #468
> [aes_mix_columns] Updated FPGA implementation report

- cava/Cava/Acorn/CavaClass.v
- cava/Cava/Acorn/CavaPrelude.v
- cava/Cava/Acorn/CombinationalMonad.v
- cava/Cava/Acorn/CombinationalProperties.v
- cava/Cava/Acorn/NetlistGeneration.v
- cava/Cava/Acorn/SequentialTimed.v
- cava/Cava/Acorn/SequentialV.v
- cava/Cava/ListUtils.v
- cava/Cava/VectorUtils.v
- silveroak-opentitan/aes/Acorn/CipherEquivalence.v
- tests/AccumulatingAdderEnable/ListProofs.v
Remove pairSel from CavaClass because it does not need an axiomatic definition because it can be defined in terms of vectors and vector indexing i.e. `indexAt`.
Some proofs will beed to be updated. @jadephilipoom please can you take care of that and if everything looks good then go ahead and merge? Thank you kindly.
> Remove pairSel from CavaClass

- cava/Cava/VectorUtils.v
- silveroak-opentitan/aes/Acorn/AES256Equivalence.v
- silveroak-opentitan/aes/Acorn/AddRoundKeyEquivalence.v
- silveroak-opentitan/aes/Acorn/FullCipherEquiv_Assumptions.out
- silveroak-opentitan/aes/Acorn/FullCipherInverse_Assumptions.out
- silveroak-opentitan/aes/Spec/AES256.v
- silveroak-opentitan/aes/Spec/StateTypeConversions.v
In #494, we added a section to `Spec/AES256.v` with a conversion to and from the representation used by OpenTitan (which is actually row-major, not column-major as in FIPS) for use with tests. A few of our circuit-equivalence axioms (`shift_rows_equiv` and `mix_columns_equiv`) were therefore incorrect as stated; they assumed a column-major order. I said I'd follow up with something that made us use this conversion everywhere and clarify our circuit specs a bit, and this is that follow-up!
Changes:
- Added specifications for all subcircuits using the new `to_flat` and `from_flat` definitions to convert back and forth between OT's representation to the flat vector used by the specs
- Change axioms in `AESEquivalence` and `add_round_key` lemma statement to use the new specifications
- …
> Correct and clear specifications for OT AES subcircuits

- cava/Cava/Acorn/Identity.v
The `simpl_ident` tactic was slow on a few goals I've tried it on, and on one seemed to even maybe be infinite-looping. It turns out we don't use the recursive cases anyway, so I've just removed them to improve the tactic's performance.
> Faster simpl_ident

- silveroak-opentitan/aes/RunningInOpenTitan.md
Instructions detailing how to run the baseline `aes_test.c` on the FPGA board as well as the Silver Oak verison.
Issue #469
> Add instructions executing aes_test.c on FPGA board

- cava/Cava/Acorn/CombinationalProperties.v
- cava/Cava/Acorn/Identity.v
- silveroak-opentitan/aes/Acorn/MixColumnsEquivalence.v
Progress on #462 
Prove `aes_mix_columns` circuit equivalent to spec in terms of two admitted lemmas about `transpose` and `aes_mix_single_column`.
@cipher1024 The `aes_transpose_correct` admit is the lemma we've talked about as a good entry point -- I'll leave it to you!
> Skeleton for mix_columns equivalence proof

- silveroak-opentitan/aes/Acorn/AES256Equivalence.v
- silveroak-opentitan/aes/Acorn/FullCipherEquiv_Assumptions.out
- silveroak-opentitan/aes/Acorn/FullCipherInverse_Assumptions.out
Equivalence proofs are still admitted, but since we now have implementations for `mix_columns` and `shift_rows` I removed the axioms in `AESEquivalence.v`. The equivalence proofs are still admitted, but at least we have some assurance that the types match and there are no more proof-slowness problems around unfolding the implementations like we had with `sub_bytes`.
> Plug in mix-columns and shift-rows implementations

- silveroak-opentitan/aes/Acorn/FullCipherEquiv_Assumptions.out
- silveroak-opentitan/aes/Acorn/FullCipherInverse_Assumptions.out
I completely missed in reviewing #532 that these files were removed. They are autogenerated files, but my argument for keeping them version-controlled is that they're a good way to track exactly what assumptions our top-level theorems depend on. And if some change introduces a new axiom (for example, one of the axioms provided by the standard library in certain imports like `Classical`), it will automatically show up here and raise the proper red flags!
> Add assumption-tracking files back to version control

- silveroak-opentitan/aes/Acorn/Cipher.v
- Additional status signals might be required for OpenTitan
- Inverse/decryption mode currently not operational
Part of #489
> Add `aes_cipher_core` without additional status signals

- silveroak-opentitan/aes/Acorn/AES256Equivalence.v
- silveroak-opentitan/aes/Acorn/FullCipherEquiv_Assumptions.out
- silveroak-opentitan/aes/Acorn/FullCipherInverse_Assumptions.out
- silveroak-opentitan/aes/Acorn/SubBytesEquivalence.v
This replaces an axiom in AES256Equivalence for the equivalence of
SubBytes with a proof.
Closes: #463
> SubBytes Equivalence

- acorn-examples/Makefile
- acorn-examples/xilinx/Makefile
- cava/Makefile
- investigations/Arrow/aes/Makefile
- investigations/Arrow/arrow-examples/Makefile
- silveroak-opentitan/aes/Acorn/Makefile
- silveroak-opentitan/aes/Spec/Makefile
- silveroak-opentitan/pinmux/Makefile
- tests/Makefile
- tests/xilinx/Makefile
Closes #472 
This change:
- declares '.v' files as prerequisites for generating _CoqProject
(avoids running rule, and thereby touching _CoqProject, if no .v
files are changed, for faster incremental builds).
- uses 'find' over 'git ls-files'. Making code git-agnostic,
specifically when creating a new file, don't need to `git add` in
order to build it.
- adds assumption that file names don't have spaces
Future considerations:
- avoid 'xilinx' subdir excludes, for consistent style
- consider factoring out file lookup logic into a define or include
which can use args or variables to specify source globs + dependency
graph (this would also make it easier to order sources - which we
now rely on being ordered alphabetically)
> _CoqProject generation w/ find.

- cava/Cava/Acorn/CombinationalPropertiesNew.v
- cava/Cava/Acorn/Combinators.v
- cava/Cava/Acorn/IdentityNew.v
Recreate new versions of `Identity.v` and `CombinationalProperties.v` that use the new purely-combinational `Cava` instance, similar to what we had before switching over to using `seqType` for everything. I also moved the `zipWith` and `xorV` lemmas to `CombinationalProperties` instead of `Identity` because I think they are better categorized there. The new files are much smaller than the old ones because of the simpler proofs and the lack of need for any proofs about `peel`, `unpeel`, `mkpair`, or `unpair`: down about 75% from a combined 764 LOC to 192.
> Parallel Identity.v and CombinationalProperties.v

- cava/Cava/Acorn/Circuit.v
- cava/Cava/Acorn/Combinational.v
- cava/Cava/Acorn/NetlistGeneration.v
- tests/DoubleCountBy/DoubleCountBy.v
- tests/DoubleCountBy/ListProofs.v
Progress on #568 
As an added bonus, this means we don't have to pass an initial state to `multistep` -- it just starts at the reset state, which can be constructed by inspecting the circuit structure.
> Add reset values to Circuits

- cava/Cava/Acorn/Circuit.v
- cava/Cava/Acorn/NetlistGeneration.v
Resolves #568 
Now we have four options for both `Loop` and `Delay`:
- `LoopInitCE` and `DelayInitCE`, with both enables and reset values, which are the base constructors in terms of which the rest are defined
- `LoopInit` and `DelayInit`, which have reset values but not enables
- `LoopCE` and `DelayCE`, which have enables but default reset values
- `Loop` and `Delay`, which have no enables and default reset values
> Add enables to Circuit

- cava/Cava/Extraction.v
- cava/Cava2HDL.cabal
- cava/Cava2SystemVerilog.hs
- cava/SystemVerilogUtils.hs
- silveroak-opentitan/aes/Acorn/AESExtraction.v
- silveroak-opentitan/aes/Acorn/AESSV.hs
- silveroak-opentitan/aes/Acorn/CipherControlCircuit.v
- silveroak-opentitan/aes/Acorn/CipherControlNetlist.v
- silveroak-opentitan/aes/Acorn/CipherNewLoop.v
- Uses instantiated versions of `aes_shift_rows`,`aes_mix_columns` etc, this is necessary to prevent excessive netlist generation (and non termination when generating SystemVerilog)
> Move control circuit to new Circuit

- cava/Cava/Acorn/Combinational.v
- cava/Cava/Acorn/CombinationalPropertiesNew.v
- cava/Cava/Acorn/IdentityNew.v
- cava/Cava/Acorn/Multistep.v
- cava/Cava/ListUtils.v
- cava/Cava/Tactics.v
- silveroak-opentitan/aes/Acorn/CipherEquivalenceNew.v
- silveroak-opentitan/aes/Acorn/CipherNewLoop.v
- tests/DoubleCountBy/DoubleCountBy.v
- tests/DoubleCountBy/ListProofs.v
Progress on #566
New, parallel version of `CipherEquivalence.v` with the `Circuit` structure. Along the way, I separated out `multistep` and a couple of proofs about it into its own file, added a new tactic `destruct_inner_pair_let`, and added some helper lemmas about lists.
> Port CipherEquivalence.v

- silveroak-opentitan/aes/Acorn/AES256EquivalenceNew.v
- silveroak-opentitan/aes/Acorn/CipherControlCircuit.v
- silveroak-opentitan/aes/Acorn/CipherEquivalenceNew.v
- silveroak-opentitan/aes/Acorn/CipherNewLoop.v
Progress on #566 
Adds a duplicate of `AESEquivalence.v` with the new `Circuit` construction. The proofs changed pretty minimally, but some of the preconditions got simpler. I ended up changing the order of arguments to `cipher` slightly to make the arguments nicer to construct, and tweaking the `cipher_equiv` proof so that we ignore the "initial state" input values after the first cycle.
> Port AESEquivalence.v to Circuit

- cava/Cava/Acorn/Combinators.v
- cava/Cava/Acorn/Multistep.v
- cava/Cava/ListUtils.v
- silveroak-opentitan/aes/Acorn/AES256EquivalenceNew.v
- silveroak-opentitan/aes/Acorn/AESSV.hs
- silveroak-opentitan/aes/Acorn/CipherControlCircuit.v
- silveroak-opentitan/aes/Acorn/CipherControlNetlist.v
- silveroak-opentitan/aes/Acorn/CipherEquivalenceNew.v
- silveroak-opentitan/aes/Acorn/CipherNewLoop.v
Resolves #560 
Resolves #414 
Makes `key_expand` a sequential `Circuit` instead of a loop, with the round constant as part of its internal state. This actually simplified the top-level lemma statements quite a bit and means we no longer need to use the "interleaved" version of the spec as an intermediate step.
> Key expansion loop

- cava/Cava/Acorn/Circuit.v
- cava/Cava/Acorn/Combinational.v
- cava/Cava/Acorn/Multistep.v
- cava/Cava/Acorn/NetlistGeneration.v
- silveroak-opentitan/aes/Acorn/CipherEquivalenceNew.v
- tests/DoubleCountBy/ListProofs.v
I realized that I made a mistake in #572 -- the way I encoded enables meant that the enable could only be a constant value, since it was part of the construction of the loop and not part of the input to the circuit. This PR fixes the issue by making enables true inputs.
Unfortunately, to make this work, I had to get rid of the cute trick where I used the same `interp` singe-step interpretation function to produce both the netlist and Coq semantics. Now we have two functions, `interpCircuit : forall i o, Circuit i o -> state CavaState o`, which creates the netlist for a `Circuit` (including constructing all the new signals and adding delays) and `step : forall i o (c : Circuit i o), circuit_state c -> i -> o * circuit_state c`, which is the single-step semantics for the identity-monad …
> Make enables a true input to loops

- cava/Cava/Acorn/AcornNew.v
- cava/Cava/Acorn/CombinationalPropertiesNew.v
- cava/Cava/Acorn/Multistep.v
- cava/Cava/Extraction.v
- cava/Cava/ListUtils.v
- cava/Cava2HDL.cabal
- tests/CountBy/CountBy.v
- tests/CountBy/ListProofs.v
- tests/DoubleCountBy/DoubleCountBy.v
- tests/DoubleCountBy/ListProofs.v
- tests/TestsExtraction.v
- tests/TestsSV.hs
Progress on #565
- Add some loop invariant lemmas for `multistep`
- Port `tests/CountBy` to `Circuit`
- Update `tests/DoubleCountBy` with netlist generation and a proof for the double counter
> Port CountBy to Circuit, update DoubleCountBy

- .gitmodules
- _CoqProject
- cava/Cava2HDL.cabal
- silveroak-opentitan/aes/Acorn/AESExtraction.v
- silveroak-opentitan/aes/Acorn/AESSV.hs
- silveroak-opentitan/aes/Acorn/CipherControlCircuit.v
- silveroak-opentitan/aes/Acorn/CipherControlNetlist.v
- silveroak-opentitan/aes/Acorn/Makefile
- third_party/Makefile
I'd hoped we could use a simpler `aes_cipher_control` with simpler signalling but after running some tests with Verilator and inspecting how the `aes_control` uses `aes_cipher_control` by observing the waveforms between the two its clear we need the full signalling. This PR removes the simpler `aes_cipher_control` and models the transition logic of the OpenTitan directly. A follow up PR will finish up connecting the pieces together again. 
What does "full signalling" mean and what does "simpler siognalling" mean? Is it's not too much bother can you share the waveform screen grabs or other output? I'm keen to understand what is going on here. Don't hold the PR up for this.
> Recreate OpenTitan aes_cipher_control state machine

- acorn-examples/AdderTree.v
- acorn-examples/Examples.v
- acorn-examples/FullAdderExample.v
- acorn-examples/IncrDecr.v
- acorn-examples/NandGate.v
- acorn-examples/UnsignedAdderExamples.v
- cava/Cava/Lib/FullAdder.v
- cava/Cava/Lib/UnsignedAdderProofs.v
- cava/Cava/Lib/UnsignedAdders.v
- cava/Cava/NatUtils.v
- tests/AddWithDelay/AddWithDelay.v
- tests/AddWithDelay/ListProofs.v
- tests/Array.v
- tests/Delay.v
Resolves #565 
There might still be some small cleanup to do, but all the proofs and large examples are now ported to `Circuit`. Once #589 is merged, we're clear to start #567.
> Port remaining tests and examples

- cava/Cava/Acorn/CavaClass.v
- cava/Cava/Acorn/CavaPrelude.v
- cava/Cava/Acorn/Combinational.v
- cava/Cava/Acorn/CombinationalProperties.v
- cava/Cava/Acorn/Combinators.v
- cava/Cava/Acorn/NetlistGeneration.v
- cava/Cava/Netlist.v
- cava/Cava/Signal.v
- cava/Cava2SystemVerilog.hs
- silveroak-opentitan/aes/Acorn/CipherCircuit.v
- silveroak-opentitan/aes/Acorn/FullCipherEquiv_Assumptions.out
- silveroak-opentitan/aes/Acorn/FullCipherInverse_Assumptions.out
Resolves #416 
Resolves #567 
With the new `Loop` infrastructure, no pairs are needed in `SignalType`! This PR removes them.
> Remove pairs from SignalType

- acorn-examples/IncrDecr.v
- acorn-examples/Sorter.v
- acorn-examples/UnsignedAdderExamples.v
- cava/Cava/Acorn/CavaClass.v
- cava/Cava/Acorn/CavaPrelude.v
- cava/Cava/Acorn/Combinational.v
- cava/Cava/Acorn/CombinationalProperties.v
- cava/Cava/Acorn/Combinators.v
- cava/Cava/Acorn/NetlistGeneration.v
- cava/Cava/Lib/UnsignedAdders.v
- silveroak-opentitan/aes/Acorn/CipherCircuit.v
- silveroak-opentitan/aes/Acorn/CipherControlCircuit.v
- silveroak-opentitan/aes/Acorn/MixColumnsCircuit.v
- silveroak-opentitan/aes/Acorn/Pkg.v
- silveroak-opentitan/aes/Acorn/ShiftRowsCircuit.v
- silveroak-opentitan/aes/Acorn/SubBytesCircuit.v
- tests/Array.v
- tests/DoubleCountBy/DoubleCountBy.v
- tests/MuxTests.v
- tests/TestMultiply.v
Updated version of #482 
Doesn't change `peel`/`unpeel`, since in discussion we weren't sure if they would need to change. @blaxill @satnam6502 , does this solve the duplicated-code problem you were seeing? Should we modify `peel`/`unpeel` as well?
> Update CavaClass to use circuits for indexing and arithmetic

- acorn-examples/AdderTree.v
- acorn-examples/IncrDecr.v
- acorn-examples/Sorter.v
- acorn-examples/xilinx/XilinxAdderTree.v
- cava/Cava/Acorn/CavaClass.v
- cava/Cava/Acorn/CavaPrelude.v
- cava/Cava/Acorn/Combinational.v
- cava/Cava/Acorn/CombinationalProperties.v
- cava/Cava/Acorn/Combinators.v
- cava/Cava/Acorn/NetlistGeneration.v
- cava/Cava/Acorn/XilinxAdder.v
- cava/Cava/Lib/UnsignedAdders.v
- silveroak-opentitan/aes/Acorn/CipherCircuit.v
- silveroak-opentitan/aes/Acorn/CipherControlCircuit.v
- silveroak-opentitan/aes/Acorn/MixColumnsCircuit.v
- silveroak-opentitan/aes/Acorn/MixColumnsEquivalence.v
- silveroak-opentitan/aes/Acorn/Pkg.v
- silveroak-opentitan/aes/Acorn/ShiftRowsCircuit.v
- silveroak-opentitan/aes/Acorn/SubBytesCircuit.v
- silveroak-opentitan/aes/Acorn/SubBytesEquivalence.v
- silveroak-opentitan/pinmux/Pinmux.v
- tests/Array.v
- tests/DoubleCountBy/DoubleCountBy.v
Follow up for #582, #596
Make `peel` and `unpeel` circuits so that they can be essentially wrapped in `localSignal` always.
@blaxill I was kind of guessing with the naming in `CipherControlCircuit`, feel free to change anything that doesn't match your conventions!
> Make peel and unpeel into circuits

- acorn-examples/IncrDecr.v
- cava/Cava/Extraction.v
- cava/Cava/Lib/Vec.v
- cava/Cava/Lib/VecProperties.v
- cava/Cava/VectorUtils.v
- cava/Cava2HDL.cabal
- silveroak-opentitan/aes/Acorn/CipherControlCircuit.v
- silveroak-opentitan/aes/Acorn/CipherControlNetlist.v
- silveroak-opentitan/aes/Acorn/MixColumnsCircuit.v
- silveroak-opentitan/aes/Acorn/MixColumnsEquivalence.v
- silveroak-opentitan/aes/Acorn/Pkg.v
- silveroak-opentitan/aes/Acorn/SubBytesCircuit.v
- silveroak-opentitan/aes/Acorn/SubBytesEquivalence.v
- tests/DoubleCountBy/DoubleCountBy.v
While trying to write a tutorial for Cava, I noticed myself writing some boilterplate `peel`s and `unpeel`s that followed similar patterns -- convert to `Vector.t`, do a vector operation, and then convert back to `Vec`. I've had the thought before that it would be nice if we had a clean library with all the `Vector.t` operations we need that does the `peel` and `unpeel` work in the background, so here it is. Now, instead of `peel >=> mapT f >=> unpeel`, you can write `Vec.map f`, and instead of `v' <- peel v ;; unpeel (x :: v')` you can write `Vec.cons x v`, and so on. There's also `Vec.bitvec_literal` for quick literal bit-vectors. The `simpl_ident` tactic will convert these definitions back to `Vector.t` automatically in proofs.
- Defines circuits for all of the `Vector.t` operations …
> Vec library

- acorn-examples/AdderTree.v
- acorn-examples/IncrDecr.v
- acorn-examples/Sorter.v
- acorn-examples/xilinx/XilinxAdderTree.v
- cava/Cava/Acorn/CavaClass.v
- cava/Cava/Acorn/Combinational.v
- cava/Cava/Acorn/Combinators.v
- cava/Cava/Acorn/Identity.v
- cava/Cava/Acorn/NetlistGeneration.v
- cava/Cava/Acorn/XilinxAdder.v
- cava/Cava/Lib/Multiplexers.v
- cava/Cava/Lib/UnsignedAdders.v
- cava/Cava/Lib/Vec.v
- silveroak-opentitan/aes/Acorn/CipherCircuit.v
- silveroak-opentitan/aes/Acorn/CipherControlCircuit.v
- silveroak-opentitan/aes/Acorn/MixColumnsCircuit.v
- silveroak-opentitan/aes/Acorn/Pkg.v
- silveroak-opentitan/aes/Acorn/ShiftRowsCircuit.v
- silveroak-opentitan/pinmux/Pinmux.v
- tests/Array.v
- tests/DoubleCountBy/ListProofs.v
Progress on #610
I have put `packv` for what used to be `unpeel` -- packaging a Coq vector into a signal -- and `unpackv` for its inverse. Does that match others' intuitions?
> Rename peel/unpeel to packv and unpackv

- silveroak-opentitan/aes/Acorn/AESSV.hs
- silveroak-opentitan/aes/Acorn/AddRoundKeyNetlist.v
- silveroak-opentitan/aes/Acorn/MixColumnsNetlist.v
- silveroak-opentitan/aes/Acorn/ShiftRowsNetlist.v
- silveroak-opentitan/aes/Acorn/SubBytesNetlist.v
- silveroak-opentitan/aes/Spec/Tests/Common.v
Currently, we're testing that the Coq semantics for our circuits match the test vectors from FIPS, but the actual test benches for the netlists only test one or two handwritten examples for each subroutine. This PR adds much more extensive test benches based on the same test data as the semantics tests.
> Create test benches based on FIPS for subroutine netlists

- acorn-examples/AdderTree.v
- acorn-examples/xilinx/XilinxAdderTree.v
- cava/Cava/Acorn/CombinationalProperties.v
- cava/Cava/Acorn/Combinators.v
- cava/Cava/Extraction.v
- cava/Cava2HDL.cabal
Side quest for #609
The motivation for this change is to clean up tree naming/input types before I write a tree example for the Cava tutorial.
- Tree combinators have been renamed:
- `pow2tree_generic` (formerly `tree`) : generic over any Coq type, requires default value, input vector must have size `2^n`
- `pow2tree` (formerly `treeS`) : specialized to `signal`, input vector must have size `2^n`
- `tree_generic` (formerly `tree_all_sizes`) : generic over any Coq type, requires default value, input vector can have any size
- `tree` (formerly did not exist) : specialized to `signal`, input vector can have any size
- `pow2tree*` combinators now accept vectors with size `2^n` instead of `2 ^(S n)`
> Renaming and tweaks to trees

- third_party/Makefile
- Bumps `coq-ext-lib` to the latest version to capture the update we submitted that prevents an infinite loop in typeclass inference
- Adds a `no-update` target to `third_party/Makefile` to make updating submodules easier
Following up from a conversation over email. @smore-lore gave an example where he was experiencing the infinite-looping problem. I reproduced the infinite loop before the update and confirmed that the update fixed it.
The change to the `Makefile` is because I realized that it was very annoying to rebuild `third_party` after updating from the remote, because the default target always ran `git submodule update` (pulling the submodule information from our repo) and undid the remote update. Now you can run `make no-update` in `third_party` to avoid this behavior.
> Update coq-ext-lib to fix infinite looping

- cava/Cava/Lib/Adders.v
- cava/Cava/Lib/AddersProperties.v
- cava/Cava/Lib/BitVectorOps.v
- cava/Cava/Lib/CavaPrelude.v
- cava/Cava/Lib/CavaPreludeProperties.v
- cava/Cava/Lib/Combinators.v
- cava/Cava/Lib/CombinatorsProperties.v
- cava/Cava/Lib/LibProperties.v
- cava/Cava/Semantics/Combinational.v
- cava/Cava2HDL.cabal
- examples/UnsignedAdderExamples.v
- examples/xilinx/XilinxAdderExamples.v
- silveroak-opentitan/aes/Impl/AddRoundKeyCircuit.v
- silveroak-opentitan/aes/Impl/AddRoundKeyEquivalence.v
Part of #639 
A set of interconnected changes that, together, hopefully make our combinators and adders more presentable, browsable, and usable.
- Remove all experimental code from `Combinators.v` and `Adders.v` -- we now have `tree` and `col` instead of six different trees and three different `col` combinators, and our adders are just `addN` (no carries) and `addC` (carries both in and out)
- Make `tree` combinator create binary trees of optimal depth for all input sizes, not just powers of 2
- Organize `Combinators.v` into logical sections
- Make xilinx adder take its carry on the right of the tuple instead of the left so that the tuple is flat (removes need for `xilinxAdderCarryFlat` in the tests to work with the netlist interface)
- Move proofs from `Combinators.v` to …
> Cleanup of Combinators.v and Adders.v

- third_party/Makefile
See https://github.com/project-oak/silveroak/issues/268#issuecomment-800531005
Not sure if this is causing the problem, but we've been getting weird build errors on `third_party` and some subdirectory targets that should be `.PHONY` aren't. It's possible that `make` is not running those targets because it thinks they are done, since the directory exists.
> Add targets to third_party .PHONY

- docs/demo/alectryon.css
- docs/demo/alectryon.js
- docs/demo/docutils_basic.css
- docs/demo/tutorial.html
Fixes #630 
Alectryon now supports the `Cmd` key for Mac users. This is the result of `make -C demos html` after updating my local alectryon to the newest version.
> Make tutorial support Mac

- third_party/Makefile
See related discussion here: https://github.com/project-oak/silveroak/issues/268#issuecomment-800498955
After I ran into the `third_party` bug we'd been seeing on CI locally, I made a quick bash script to run the `make` repeatedly so I could see if the transient bug still existed. This change seems to fix the problem; I ran the bug-finding script on the current `main` and found the transient bug 7 times in 100 runs, and found it 0 times with the fix.
> Make bedrock2 target depend on coqutil

- cava/Cava/Lib/VecConstEq.v
Implement an efficient constant equality for vectors #657
Currently we compare against `nat`s, so the constants can be out of range (in
which case they're truncated). Eventually these should be replaced by
`Fin 2^n`s, which should prevent this.
> Add Cava.Lib.VecConstEq

- demos/tutorial.v
- docs/demo/tutorial.html
For #609 
- Add a short warning about `Vec` vs `Vector` based on feedback from @atondwal 
- Add a couple sentences showing + explaining the `Cava` imports, instead of hiding them
> Add extra information on imports + vectors to the tutorial

- cava/Cava/Lib/Adders.v
- cava/Cava/Lib/AddersProperties.v
- cava/Cava/Util/BitArithmeticProperties.v
- cava/Cava/Util/Vector.v
Resolves #474 
This incrementer (unlike the version in `examples/IncrDecr.v`) uses the synthesizable adder. I wanted an incrementer for a tutorial example, and it seemed like a good thing to add to our library anyway. Following the same pattern as our bit-vector adders `addN` and `addC`, there's one incrementer that has a carry bit to indicate overflow (`incrC`), and one without a carry (`incrN`).
> Add and prove an incrementer

- cava/Cava2HDL.cabal
- silveroak-opentitan/aes/Impl/AESExtraction.v
- silveroak-opentitan/aes/Impl/AESSV.hs
- silveroak-opentitan/aes/Impl/CipherControlCircuit.v
- silveroak-opentitan/aes/Impl/FFunctor.v
- Add comments to control logic definitions
- Add 'FFunctor'/etc classes, these are more generalized version of the classes from `coq-ext-lib`. I've added them to make explicit their structure that I was already using in the control logic and to clean up my adhoc naming a bit.
> Add comments to control circuit and small cleanup

- cava/Cava/Core/CavaClass.v
- cava/Cava/Lib/Vec.v
- cava/Cava/NetlistGeneration/NetlistGeneration.v
- cava/Cava/Semantics/Combinational.v
- docs/reference.md
- silveroak-opentitan/aes/Impl/CipherControlCircuit.v
- silveroak-opentitan/aes/Impl/Pkg.v
- tests/Array.v
While trying to demonstrate loops with initial values, I noticed an inconvenient feature of our current setup. Loops and delays take `signal t` as their reset value, see here:
https://github.com/project-oak/silveroak/blob/e83fe025e5186c59ea6e31256f4c2f8f86cc5505/cava/Cava/Core/Circuit.v#L36-L42
However, in the usual circuit-definition context with a completely abstract `cava` monad, it's impossible to construct a `signal (Vec _ _)` that doesn't have a `cava` wrapped around it (since #597, `packV` wraps vectors in `cava`).
This PR introduces the ability to construct _constant_ vectors with `constantV`, similar to `constant` for bits. It comes at the cost of a new field for `CavaClass`.
@blaxill If you have a moment, it would be nice to confirm that this change doesn't affect the resource …
> Add constantV to CavaClass

- cava/Cava/Core/Circuit.v
- cava/Cava/Core/Netlist.v
- cava/Cava2HDL.cabal
- cava/Cava2SystemVerilog.hs
As per https://github.com/project-oak/silveroak/pull/681#issuecomment-804307948
@satnam6502 @blaxill I'm not Haskell-literate enough to fix the `Cava2SystemVerilog` error here, could one of you help?
> Make delay and loop reset states combType instead of signal

- demos/tutorial.v
- docs/demo/tutorial.css
- docs/demo/tutorial.html
Fixes #694 
There ended up being a much simpler solution to this problem than I originally thought; I can just add a `.. raw:: html` block and a custom stylesheet that overrides the arrow-stylization.
> Add tutorial stylesheet

- demos/tutorial.v
- docs/demo/tutorial.html
Locally, `/reference` linked to the reference sheet, but on the live page it links to `https://project-oak.github.io/reference` instead of `https://project-oak.github.io/silveroak/reference`. Changing to a relative path instead so that it works in both places.
> Fix reference link in tutorial

- cava/Cava2SystemVerilog.hs
- examples/BitonicSorter.v
- examples/ExamplesSV.hs
- examples/MonadExtraction.v
Also discard empty vectors when generating SystemVerilog.
Test passes!
```
clang++ -L/usr/local/opt/sqlite/lib    bsort4_8_tb.o verilated.o verilated_vcd_c.o Vbsort4_8_tb__ALL.a    -o Vbsort4_8_tb -lm -lstdc++
obj_dir/Vbsort4_8_tb
10: tick = 0,  inputs[0] = 12,  inputs[1] = 2,  inputs[2] = 11,  inputs[3] = 10,  inputs[4] = 16,  inputs[5] = 14,  inputs[6] = 6,  inputs[7] = 3,  inputs[8] = 5,  inputs[9] = 1,  inputs[10] = 7,  inputs[11] = 15,  inputs[12] = 9,  inputs[13] = 13,  inputs[14] = 4,  inputs[15] = 8, 
sorted[0] = 1,  sorted[1] = 2,  sorted[2] = 3,  sorted[3] = 4,  sorted[4] = 5,  sorted[5] = 6,  sorted[6] = 7,  sorted[7] = 8,  sorted[8] = 9,  sorted[9] = 10,  sorted[10] = 11,  sorted[11] = 12,  sorted[12] = 13,  sorted[13] = 14,  sorted[14] = 15,  sorted[15] = 16
PASSED
```
CC: …
> SystemVerilog test for bsort

- docs/Gemfile.lock
Address:
```
1 kramdown vulnerability found in docs/Gemfile.lock 7 hours ago
Remediation
Upgrade kramdown to version 2.3.1 or later. For example:
gem "kramdown", ">= 2.3.1"
Always verify the validity and compatibility of suggestions with your codebase.
Details
CVE-2021-28834
high severity
Vulnerable versions: >= 1.16.0, < 2.3.1
Patched version: 2.3.1
Kramdown before 2.3.1 does not restrict Rouge formatters to the Rouge::Formatters namespace, and thus arbitrary classes can be instantiated.
```
> Fix kramdown security vunrelability

- demos/tutorial.v
- docs/demo/tutorial.html
Tutorial is updated to:
- advise mobile users that they can tap on a line to see the Coq output
- link to Alectryon in the text (got a few people asking me how "I" did the Coq output feature, so I think it makes sense to add a link more prominent than the one in the banner at the top)
- change `About inv` to `Check inv` to reduce the amount of unnecessary information printed
Also updates the HTML to include changes from #714
> Incorporate some feedback on the tutorial

- silveroak-opentitan/aes/.gitignore
- silveroak-opentitan/aes/Makefile
- silveroak-opentitan/aes/RunningInOpenTitan.md
- silveroak-opentitan/aes/configure_opentitan_verilator.sh
- silveroak-opentitan/aes/copy_silveroak_files.sh
- silveroak-opentitan/aes/diff_opentitan_silveroak.sh
- silveroak-opentitan/aes/prepare_silveroak_items.sh
- silveroak-opentitan/aes/run_in_opentitan.sh
- Update `silveroak-opentitan/aes` bash files
- Add `make diff_opentitan` to `silveroak-opentitan/aes/Makefile`
This will create copies of `third_party/opentitan` as subdirectories `opentitan_gold` and `opentitan_silveroak` in `silveroak-opentitan/aes` with `opentitan_silveroak` containing silveroak replacements. Both directories should be buildable.
- Update doc
#722
> Add files for OpenTitan {gold,silveroak} comparison

- silveroak-opentitan/aes/Impl/Makefile
- silveroak-opentitan/aes/Impl/SubBytesCircuit.v
A bit of an extraction experiment: Having `nats` in extraction code is slow. This includes as constants and indices to vectors. I only modified SubBytes here as it was the easiest to modify, but it knocked 20s off `ghc --make`. Test vectors for `MixColumns` and `AddRoundKeyNetlist` are unmodified (they include vecs with nat indices) and still extract slow. Parallel ghc (`ghc -j`) halves the execution time.
> Performance tweaks for Haskell execution

- investigations/bedrock2/IncrementWait/IncrementWait.v
- investigations/bedrock2/IncrementWait/IncrementWaitProperties.v
- investigations/bedrock2/IncrementWait/IncrementWaitSemantics.v
- investigations/bedrock2/incrementwait.c.out
In #729 I mentioned that the bedrock2 firmware experiment had a bit of a hacky solution in it to prove that its while loop terminated; the program took an argument that was a maximum number of times to try reading the result before giving up. This PR fixes that and changes the loop to a more realistic `while (true)` loop. The logic is now much more similar to `aes.c`.
Although the software is still not directly aware of circuit timing information, the circuit specification now includes, for the `BUSY` state, a maximum number of future reads that can happen before the state is `DONE` (the circuit is permitted to move to the `DONE` state sooner). It should be possible to prove that a circuit meets this specification by simply plugging in the number of cycles for the maximum reads; each read …
> Use a while(true) loop in bedrock2 experimental circuit

- investigations/bedrock2/IncrementWait/IncrementWait.v
- investigations/bedrock2/IncrementWait/IncrementWaitProperties.v
- investigations/bedrock2/IncrementWait/IncrementWaitSemantics.v
- investigations/bedrock2/IncrementWait/IncrementWaitToC.v
- investigations/bedrock2/incrementwait.c.out
Alternative to #737; only one of the two should be merged.
This solves the same problem as #737 but with a different method. Here, the constants are interpreted as _arguments_ to the function, both in the C printout and in the proofs. The C printout looks like:
```
uintptr_t put_wait_get(uintptr_t VALUE_ADDR, uintptr_t STATUS_ADDR, uintptr_t STATUS_IDLE, uintptr_t STATUS_BUSY, uintptr_t STATUS_DONE, uintptr_t input) {
uintptr_t status, out;
REG32_SET(VALUE_ADDR, input);
status = (uintptr_t)0ULL;
while (((status)&(((uintptr_t)1ULL)<<(STATUS_DONE)))==((uintptr_t)0ULL)) {
status = REG32_GET(STATUS_ADDR);
}
out = REG32_GET(VALUE_ADDR);
return out;
}
```
Compared to #737, this solution:
- (+) avoids the issue in #737 where overwriting global constants can lead to discrepancies between C and …
> Option 2 of 2: Interpret bedrock2 constants as arguments

- .gitignore
- cabal.project
- cava/Makefile
- default.nix
- examples/Makefile
- examples/cava-examples.cabal
- silveroak-opentitan/aes/Impl/Makefile
- silveroak-opentitan/aes/silveroak-aes.cabal
- silveroak-opentitan/pinmux/Makefile
- silveroak-opentitan/pinmux/silveroak-pinmux.cabal
- tests/Makefile
- tests/cava-tests.cabal
- Removes the requirement to install Cava2HDL globally
#742
> Add cabal support to Haskell modules

- README.md
- cava/Cava2HDL.cabal
- default.nix
- docs/index.md
- third_party/Makefile
~Testing CI, please ignore for now.~ CI passed!
Resolves #730 
This PR upgrades us to use Coq 8.13 in the CI. It is most likely not a backwards-compatible change due to a change to module names in the Haskell extraction, and possibly also due to the coq-record-update upgrade that was needed for 8.13 to build. Before this PR is merged, everyone should update their local development environment to 8.13 or higher. I've upgraded mine to 8.13.2 and everything builds, so any 8.13.x version is likely fine.
> Upgrade to Coq 8.13

- tests/Makefile
Looks like this line escaped the rename in #744, got some build warnings
> Rename ip -> IP in tests/Makefile

- investigations/bedrock2/Aes/Aes.v
- investigations/bedrock2/Aes/AesProperties.v
- investigations/bedrock2/Aes/AesSemantics.v
- investigations/bedrock2/Tactics.v
Very similar to #765, but for reading output data instead of writing input data.
With this, we have a more-or-less complete version of OpenTitan's `aes.c` :tada: (we're missing `aes_clear`, but the simplified AES state machine I'm using for these proofs doesn't have a clearing functionality).
The next steps I'm thinking of taking from here are:
- Plug this code into `aes.c` and check that we pass the AES tests
- Prove the admitted bit-arithmetic lemmas in `Word.v`
- Change the `aes_key_put` proof, which takes quite a while to check because it destructs into 3 cases of key length * 8 loop iterations per case, into a proof using a loop invariant
- Add a test program that composes operations from the `aes.c` API (e.g. initialize, write IV and key registers, write input, wait for output, read …
> [investigations] Implement + prove aes_data_get and aes_data_get_wait

- investigations/bedrock2/Aes/Aes.v
- investigations/bedrock2/Aes/AesExample.v
- investigations/bedrock2/Aes/AesExampleProperties.v
- investigations/bedrock2/Aes/AesProperties.v
This program serves as sort of a test that the AES API proofs compose together properly. The example program initializes the AES block, writes the key, IV, and input registers, waits for the output, and reads the results into an array pointer provided by the caller. The specification says that the circuit is idle, the input arrays (keys, IV, and input) are unchanged, and the result array pointer now points to values that match the AES specification for the inputs (the specification in terms of words is provided by the `AesSemantics.parameters` instance in terms of words; we could plug in Cava's AES specification by making an instance of the parameters for it, but I haven't done so here because I think it's nicer for the proofs to be parameterized over how one chooses to express the spec). …
> Add AES example program

- investigations/bedrock2/Aes/AesProperties.v
- investigations/bedrock2/StateMachineProperties.v
- investigations/bedrock2/WhileProperties.v
- investigations/bedrock2/WordProperties.v
As discussed in #766 
- Prove some previously admitted bit-arithmetic lemmas
- Change the `aes_key_put` proof to use a loop invariant instead of unrolling the loop (this was low-hanging fruit to make the `AesProperties.v` file run in a more reasonable amount of time; on my machine the compilation time went from 2min30s to 1min30s)
There are other things that can be done to clean up/speed up the code here, but this resolves the issues I considered hard blockers to moving the code out of `investigations/`.
> Prove remaining admits and improve speed of bedrock2 experiments

- README.md
Resolves #783 
As a long-term solution I'd still like to make this process more automatic and not require potentially new contributors to install Alectryon locally (see #780), but this documents the current process.
> Add alectryon build instructions to README

- investigations/bedrock2/IncrementWait/Constants.v
- investigations/bedrock2/IncrementWait/IncrementWaitMMIO.v
- investigations/bedrock2/IncrementWait/IncrementWaitToRiscV.v
- investigations/bedrock2/IncrementWait/IncrementWaitToRiscVProperties.v
- investigations/bedrock2/List.v
This PR builds on #792 to write a fully-instantiated correctness proof for the assembly code in the increment-wait minimal example, in order to make sure that everything ties together and all of the compiler proofs' preconditions are satisfied.
- Creates a `main` function that simply reads an input value from a constant location in memory, calls `put_wait_get`, and stores the output to another constant location in memory (the `main` function is not allowed to have arguments)
- Compiles the `main` function and the `put_wait_get` function together
- Proves that, if the input/output pointers are valid, a RISC-V machine executing the resulting assembly will remain in a valid state and satisfy the postcondition of `main` (which says that the circuit has returned to the IDLE state, the value at …
> Instantiate compiler correctness proof for increment-wait

- investigations/bedrock2/Aes/Aes.v
- investigations/bedrock2/Aes/AesExampleProperties.v
- investigations/bedrock2/Aes/AesProperties.v
- investigations/bedrock2/Aes/AesSemantics.v
- investigations/bedrock2/Aes/Constants.v
- investigations/bedrock2/StateMachineProperties.v
- investigations/bedrock2/StateMachineSemantics.v
- investigations/bedrock2/WhileProperties.v
- investigations/bedrock2/WordProperties.v
This PR contains some changes to the AES semantics and proofs that match the changes I made earlier to the increment-wait example circuit (see e.g. #792) so that it would be compatible with the bedrock2 compiler proofs. (The `ext_spec` definition forms part of the interface between program and compiler proofs; the previous version worked for proofs of programs but wouldn't have been strong enough to work with the compiler proofs.) This paves the way for actually compiling our AES code and getting proofs about the assembly.
Some of the code churn here is a change to how the state data (e.g. register values) is represented; since I was changing all these proofs anyway, it seemed worth a refactor because this representation was a major pain point before. Still not necessarily totally happy …
> Update AES semantics to be compatible with compiler proofs

- investigations/bedrock2/Aes/AesExampleProperties.v
- investigations/bedrock2/Aes/AesProperties.v
- investigations/bedrock2/Aes/AesSemantics.v
- investigations/bedrock2/Aes/AesToC.v
- investigations/bedrock2/Aes/Constants.v
- investigations/bedrock2/StateMachineMMIO.v
- investigations/bedrock2/StateMachineProperties.v
- investigations/bedrock2/StateMachineSemantics.v
- Adds `StateMachineMMIO.v`, which constructs the compiler setup for the generic state-machine semantics used by AES and proves a key lemma that says the compiler compiles MMIO interactions correctly. This file is almost exactly a copy of `IncrementWaitMMIO.v`, which is itself based on bedrock2's `compilerExamples/MMIO.v`.
- Threads a few compiler preconditions (e.g. MMIO addresses are word-aligned) through the state machine semantics and AES proofs.
- Fixes the `aes.c` template to use "MMIOREAD" and "MMIOWRITE" (should have been in #800, missed this in the previous changes)
The fact that this proof passes means that the firmware/hardware interface is set up in a way that's compatible with the compiler (i.e. #800 worked)!
> State machine mmio

- investigations/bedrock2/Aes/Aes.v
- investigations/bedrock2/Aes/AesExample.v
- investigations/bedrock2/Aes/AesExampleProperties.v
- investigations/bedrock2/Aes/AesProperties.v
- investigations/bedrock2/Aes/AesToRiscV.v
Compile the AES firmware to assembly! :tada: 
Unfortunately, the bedrock2 compiler has a restriction on the number of arguments a function can have (arguments + return values + 5 < 32), which meant the previous strategy of passing all global constants into all functions would result in too many arguments. This PR therefore modifies each function to take only the globals it actually needs as arguments.
> Compile AES code

- investigations/bedrock2/Aes/AesExampleProperties.v
- investigations/bedrock2/Aes/AesExampleToRiscV.v
- investigations/bedrock2/Aes/AesExampleToRiscVProperties.v
- investigations/bedrock2/Aes/AesToRiscV.v
- investigations/bedrock2/Aes/Constants.v
- Compiles the AES example program (which uses the AES API to perform a full round of encryption)
- Uses the bedrock2 compiler proofs to show that the compiled assembly has the expected behavior
Right now, the specification that describes what exactly the circuit does with the input is an axiom. I think a good next step from here would possibly be to plug in the real AES spec from our circuit verification, create an example program that runs _decryption_, and prove that composing the two is the identity all the way at the assembly level -- that would give us some assurance that we can build on top of the proofs.
> Proofs about AES assembly

- cava/Cava/CavaProperties.v
- cava/Cava/Lib/CircuitTransforms.v
- cava/Cava/Lib/CircuitTransformsProperties.v
- cava/Cava/Lib/Lib.v
- cava/Cava/Semantics/Equivalence.v
Resolves #808
It's now possible to rewrite circuit expressions using some lemmas about their behavior. For instance, if you have an expression in your goal like:
```
simulate (c1 >==> Loop (c2 >==> First (c3 >==> c4)) input
```
... you can do `rewrite First_Compose` to get:
```
simulate (c1 >==> Loop (c2 >==> First c3 >==> First c4) input
```
.. or, you could go more automatic -- write `autorewrite with circuitsimpl push_loop` to get:
```
simulate (c1 >==> Loop c2 >==> c3 >==> c4) input
```
I expect this infrastructure to make proofs about circuit retiming much easier.
> Circuit equivalence relation

- nix/sources.json
Pin nixpkgs to make sure binary derivations remain available.
> Pin sources

- firmware/LibBase/BitfieldProperties.v
- firmware/README.md
Specification & proofs has been added for the following functions:
- bitfield_field32_write
- bitfield_bit32_write
The postcondition just states that the return value is basically what is
computed in the function body, which might be not very useful for its
callers. We will add or modify the postcondition later if needed.
This compliments #849
> Finish BitfieldProperties by adding spec of write functions

- silveroak-opentitan/hmac/Spec/SHA256.v
For #869 
I tested this on one example vector and it works, more rigorous testing to come later! I defined some local, only-parsing notations to keep as close to the FIPS document as possible. Overall it's pretty concise, around 200 lines, with imports only from the standard library.
> Full SHA-256 spec

- silveroak-opentitan/hmac/Spec/HMAC.v
- silveroak-opentitan/hmac/Spec/SHA256.v
- silveroak-opentitan/hmac/Spec/Tests/HMACTestVectors.v
- silveroak-opentitan/hmac/Spec/Tests/HMACTests.v
- silveroak-opentitan/hmac/Spec/Tests/SHA256TestVectors.v
- silveroak-opentitan/hmac/Spec/Tests/SHA256Tests.v
Resolves #876 
- Transcribes test vectors from NIST documents for HMAC and SHA-256, in such a way that intermediate values can also be checked for debugging purposes
- Runs the tests on SHA-256 and HMAC specifications
- Adjusts the HMAC specification to handle keys with a length greater than `B`
> Robust testing for HMAC and SHA-256

- investigations/cava2/Expr.v
- investigations/cava2/Fib.v
- investigations/cava2/Fifo.v
- investigations/cava2/Hmac.v
- investigations/cava2/Semantics.v
- investigations/cava2/Sha256.v
- investigations/cava2/TLUL.v
This allows us to write constants without a cast, ie instead of `Constant (literal : denote_type T)` we simply can write `Constant T literal`, thus saving us a `:`, a pair of parentheses, and a `denote_type`.
In the rare cases where the value passed to `Constant` has already a type of the form `denote_type _`, this approach costs us one `_`: Instead of `Constant value`, we now have to write `Constant _ value`.
Compared to https://github.com/project-oak/silveroak/pull/868, this is still a bit more verbose, but has about one fewer bell and whistle :wink:
> make type argument of `Constant` explicit

- silveroak-opentitan/hmac/Spec/SHA256Properties.v
The SHA-256 spec stipulates that the `k` parameter be the smallest possible solution to a particular equation, but doesn't give an explicit formula. I've proven here that the formula I used in the spec produces the smallest possible solution. The proofs are pretty ugly because of a lack of automation for `Z.to_N` and `Z.of_N`, but since we don't really do other proofs with `Z` I'm not sure it's worth the added effort to change that.
> Proofs about SHA-256 spec

- investigations/cava2/Expr.v
- investigations/cava2/Fifo.v
- investigations/cava2/Hmac.v
- investigations/cava2/Primitives.v
- investigations/cava2/Semantics.v
- investigations/cava2/Sha256.v
- investigations/cava2/TLUL.v
- investigations/cava2/Types.v
Resolves #877 
- Makes `BitVec` a constructor of the `type` inductive, replacing `Bit`
- Removes `simple_denote_type`; it's no longer necessary if `BitVec` is always `N` and `Vec` is always `list`
- Removes `take` and `drop` in favor of `skipn` and `firstn` (they appeared to be exactly equivalent; any reason to use our own custom definitions instead of the standard library here?)
- Adjusts primitives so that "arithmetic"-type operations (e.g. shifting, addition, bitwise operations) are defined only on `BitVec`, and "vector"-type operations (e.g. uncons, reverse) are defined only on `Vec`; some operations, such as resizing and concatenation, are defined on both
- Adapts circuits to new setup
@blaxill the intermediate tests for `sha_inner` and `sha_padder` are working, but `sha256` isn't …
> Uncouple BitVec and Vec

- cava/Cava/Util/BitArithmetic.v
- cava/Cava/Util/String.v
- silveroak-opentitan/hmac/Spec/HMAC.v
- silveroak-opentitan/hmac/Spec/SHA256.v
- silveroak-opentitan/hmac/Spec/SHA256Properties.v
- silveroak-opentitan/hmac/Spec/Tests/HMACTestVectors.v
- silveroak-opentitan/hmac/Spec/Tests/HMACTests.v
- silveroak-opentitan/hmac/Spec/Tests/SHA256TestVectors.v
- silveroak-opentitan/hmac/Spec/Tests/SHA256Tests.v
Implements the change discussed in https://github.com/project-oak/silveroak/pull/872#issuecomment-896059991
This changes the SHA-256 and HMAC specifications so that they take their inputs as lists of bytes (instead of a length parameter and an `N`). SHA-256 internally then converts the input to `N` after padding, which seems to strike a nice balance between doing logically-bytewise operations on bytes and logically-numeric operations on `N`. It should also make the bedrock2 interface smoother.
> Modify SHA-256 and HMAC specs to have interfaces based on bytes

- investigations/cava2/Expr.v
- investigations/cava2/Primitives.v
- investigations/cava2/Semantics.v
- investigations/cava2/Sha256Properties.v
- investigations/cava2/TLUL.v
- investigations/cava2/Types.v
- investigations/cava2/_CoqProject
- silveroak-opentitan/hmac/Spec/SHA256.v
As the first major circuit proofs using cava2, this also involved making some infrastructure improvements:
- Circuit type notations were globally `Open`ed in the `Types.v` file, meaning that anyone importing that file (even transitively) couldn't disable them. They directly conflict with list notations, so this was problematic. Instead, I've used `Bind Scope` to make Coq automatically interpret things it knows are `type`s in `circuit_type_scope`. The previous behavior can be recreated using `Local Open Scope circuit_type_scope`, but in practice the `Bind Scope` was enough in most places.
- Moved the various primitive circuits out of `PrimitiveNotations` so that it's possible to not import `PrimitiveNotations` (in proofs, I find circuit notations are unhelpful because I just translate it …
> Prove sha256_compress correct

- investigations/cava2/Expr.v
- investigations/cava2/Sha256Tests.v
For #880 
Attempting to run the SHA-256 test vectors on the circuit. Two problems I'd like help on (@blaxill ?):
- I can't figure out how long the circuit is expected to run; test1 ("abc", 1 block, 3 bytes) takes `64*1+17` cycles, but test2 (2 blocks, 14 bytes) takes `64*2+21`. For bigger tests I can't tell, because...
- When I try to run test3, the circuit doesn't ever switch the "done" flag to 1, even when run for 500 cycles, and as far as I can tell doesn't ever get to the correct answer. I also tried running a 4-block test (the 4-byte word derived from "abcd" repeated 48 times) with the same result; it didn't ever seem to finish the computation.
> Run SHA-256 test vectors on circuit

- cava2/Primitives.v
Noticed this as I was browsing the code. Basically, Coq's addition and subtraction for `N` is left-associative, so the current implementation doesn't protect from underflow since it groups as `((x - y) + 2 ^ n) mod 2 ^ n`.
Specific example of the problem (`n=3`):
```coq
Compute ((2 - 3 + 8) mod 8)%N. (* 0 *)
Compute ((2 + 8 - 3) mod 8)%N. (* 7 *)
```
> Fix subtraction underflow bug

- cava2/Expr.v
- cava2/Fifo.v
- cava2/Primitives.v
- cava2/Semantics.v
- cava2/TLUL.v
- cava2/Types.v
- silveroak-opentitan/hmac/hw/Hmac.v
- silveroak-opentitan/hmac/hw/Sha256.v
- silveroak-opentitan/hmac/hw/Sha256Properties.v
- silveroak-opentitan/hmac/hw/Sha256Tests.v
See discussion https://github.com/project-oak/silveroak/pull/904#discussion_r690325205
Earlier I removed `Bit` and replaced it with `BitVec 1`, with the rationale that this would make our core type system simpler. It does, but it also makes individual proofs harder because you end up doing case analysis on an `N` which really you only expect to be a 0 or 1. I tried out adding `Bit` back as a separate type that is denoted as `bool`, and I think overall the wins for simplicity of invariants etc are worth it, so I suggest we add it back!
> Re-add Bit type and adapt proofs/circuits

- cava2/Expr.v
- cava2/TLUL.v
- firmware/IncrementWait/CavaIncrementDevice.v
- silveroak-opentitan/hmac/hw/Hmac.v
- silveroak-opentitan/hmac/hw/Sha256Properties.v
Currently, the `True` and `False` constant circuits defined in `Expr.v` mask the definitions of `True` and `False` in Coq's core logic, meaning that if `Expr.v` is imported then you have to write `Logic.True` and `Logic.False`. It's a bit annoying and makes specifications/invariants/proof states less readable. (Some Coq IDE setups, including mine, display `True` and `False` as unicode logical symbols, which makes circuits less readable as well.)
Are these names a suitable alternative?
> Rename True and False constant circuits to One and Zero

- silveroak-opentitan/hmac/Spec/Tests/SHA256TestVectors.v
- silveroak-opentitan/hmac/Spec/Tests/SHA256Tests.v
- silveroak-opentitan/hmac/hw/Sha256.v
- silveroak-opentitan/hmac/hw/Sha256Tests.v
While trying to prove the circuit correct, I found that there was a bug in the case where the circuit needs to switch from the "emit_bit" state directory to "writing_length" (occurs if there's exactly one word between the message and length). This PR fixes the bug and adds a regression test.
> Fix bug in SHA-256 padder

- cava/Cava/Util/BitArithmetic.v
- silveroak-opentitan/hmac/hw/Sha256Properties.v
Another update on the padder proofs:
- All the scariest admits from the invariant-preservation proof are now proven
- Half of the padder output-correctness proof is sketched out with a few admits
Everything seems to be on track so far, although the bit-fiddling is annoying in the `is_final` case. Mostly automated now, but we could go farther.
> Partial padder output correctness proof

- silveroak-opentitan/hmac/hw/Sha256.v
Found another small bug in the padder while working on the proofs. (No regression test this time because it's only triggered when the input is huge, so just computing the test would take ages.)
The `length` variable indicates the length of the message in bytes, and is a bit-vector with size 61. At the end of the padding routine, we shift it by 3 to get the length of the message in _bits_, and want to end up with a 64-bit vector. However, the shift-left routine produces output that is the same size as its input, so it truncates the result to 61 bits here; if the length in bytes is greater than 2^58, the length in bits is > 2^61, and will be improperly truncated. Resizing `length` to 64 bits before shifting fixes the problem.
> Fix padder bug

- silveroak-opentitan/hmac/hw/Sha256.v
- silveroak-opentitan/hmac/hw/Sha256Properties.v
On top of #925 (will be marked draft until #925 is merged).
Padder proofs are now done except for a few lemmas that are not padder-specific (they're only about `N`, `bytes`, `nat`, etc). The full output from `Print Assumptions` is:
```coq
nth_firstn
: forall (A : Type) (i n : nat) (d : A) (l : list A),
nth i (firstn n l) d = (if i <? n then nth i l d else d)
nth_bytes_to_Ns
: forall (i n : nat) (bs : list byte),
nth i (BigEndianBytes.bytes_to_Ns n bs) 0%N =
BigEndianBytes.concat_bytes (List.map (fun j : nat => nth (i * n + j) bs "000"%byte) (seq 0 n))
ceiling_range : forall a b : nat, 0 < b -> 0 < a -> Nat.ceiling a b * b - b < a <= Nat.ceiling a b * b
ceiling_add_same
: forall a b c : nat, 1 < c < b - 1 -> a mod b <= b - c -> Nat.ceiling (a + c) b = Nat.ceiling (a + 1) b …
```
> Complete padder proofs

- cava2/ExprProperties.v
- silveroak-opentitan/hmac/hw/Sha256Properties.v
Cleanup after #926, just moving some general-purpose lemmas about bitvector primitives into the cava2 main library.
> Move some lemmas to cava2/ExprProperties.v

- cava2/Expr.v
- cava2/FifoProperties.v
- cava2/Semantics.v
- cava2/Types.v
- silveroak-opentitan/hmac/hw/Hmac.v
- silveroak-opentitan/hmac/hw/Sha256Tests.v
Currently, we have a `tvar` typeclass that should help us infer type denotation definitions, but no instances of the typeclass are ever constructed (although they do exist inside sections). Making `denote_type` an instance of `tvar` means we can remove a lot of `(var:=denote_type)` clauses, which seems like an improvement.
> Make use of tvar typeclass

- cava/Cava/Util/Nat.v
- cava2/ExprProperties.v
- cava2/Invariant.v
I've been thinking that we should probably introduce some more structure and ergonomics to the invariant-style reasoning we've been loosely using. So I created some small examples that test the kind of things we want invariant reasoning to be able to do, including handle abstract types and subcircuits.
I've got a certain typeclass-based setup working on the examples, and added some automation. But I think before we commit to this kind of setup, it's worth having a little bit of design discussion about it. The two examples should let us iterate more quickly on ideas in this area.
> More structured invariant-reasoning infrastructure with examples

- silveroak-opentitan/hmac/hw/Sha256Properties.v
I was looking at the padder proofs and realized that in #926 I had a typo and accidentally pushed the wrong branch (`sha-padder-proofs4` instead of `sha-padder-proofs5`, that's what I get for non-descriptive branch names). The version that got merged was the first draft of the full proofs with still a number of padder-specific admits; this updated version has the admits factored into the small set discussed in #926. Sorry for the mixup!
> Fix padder proof admits

- silveroak-opentitan/hmac/hw/Sha256Properties.v
The base case of the invariants still needs to be proven, but those should be easy. There's a lot of code churn, but it's mostly just formatting changes. Overall this porting went pretty smoothly, and should make the proofs considerably easier to use because `sha256_inner` actually depended on its own internal state for its output specification before (no longer necessary because now that we have postcondition-style reasoning, we can avoid having to construct the output for cases where we don't care about it).
> Port existing SHA-256 proofs to new invariant infrastructure

- cava/Cava/Util/BitArithmeticProperties.v
- cava/Cava/Util/List.v
- cava/Cava/Util/Nat.v
- silveroak-opentitan/hmac/Spec/SHA256Properties.v
- silveroak-opentitan/hmac/hw/Sha256Properties.v
I needed some of the same helper lemmas to adjust some of the other proofs and start with the outer `sha256` circuit, so it made sense to just prove them and move them to the appropriate files. Padder proofs are now closed under the global context :tada:
> Prove and reorganize all padder helper lemmas

- silveroak-opentitan/hmac/Spec/SHA256.v
- silveroak-opentitan/hmac/Spec/SHA256Properties.v
- silveroak-opentitan/hmac/hw/Sha256Properties.v
In preparation for proving `sha256`, I realized it would be helpful to change the phrasing of `sha256_inner`'s specification. In particular:
1. The abstract state should reference the message _seen so far_, not the whole message, because `sha256` won't know the whole message if it's only gotten part of the data
2. The postcondition should be in terms of `sha256_step`, not `sha256_compress`, just to make the logic a little smoother
Change (2) was pretty straightforward, but change (1) was more complicated. Basically, the `sha256_inner` circuit really should only reason about the _padded_ message, which is its input, not whatever original message the padded message came from. But this was problematic because the specs require the original message; I couldn't describe what `sha256_step` …
> Adjust sha256_inner proofs

- cava2/Components/Fifo.v
- cava2/Components/FifoProperties.v
- cava2/Components/RealignFifo.v
- cava2/Components/RealignFifoProperties.v
- cava2/Components/Realigner.v
- cava2/Components/RealignerProperties.v
- silveroak-opentitan/hmac/hw/Hmac.v
- silveroak-opentitan/hmac/hw/Sha256.v
This splits `fifo` `realign` and `realign_fifo` into separate files for easier manipulation (as some of the proof terms are slow), and also adds a spec and proof for `realign_fifo` in terms of the `fifo` and `realign` specs.
> Add realign_fifo spec and proof

- silveroak-opentitan/hmac/Spec/SHA256Properties.v
- silveroak-opentitan/hmac/hw/Sha256.v
- silveroak-opentitan/hmac/hw/Sha256Properties.v
This is my work on the sha256 proof so far, to be updated a little more before I unmark as draft.
What's done right now:
- Invariant and specification are written
- Invariant-holds-at-reset is proved
- Certain subclauses of the invariant preservation proof (I tried to do the hardest bits first):
- proofs that the subcircuits' preconditions are satisfied (this required some tweaks to subcircuit specifications and proofs)
- proofs that the subcircuits' invariants are always satisfied (this also required some tweaks to subcircuit specifications and proofs)
- All invariant clauses for the case where `count=0`; there are three other cases (`0 < count <= 15`, `count=16`, and `count=17`) but most of the clauses are similar, so the `count=0` case should hopefully provide a helpful example for …
> Partial version of sha256 proof

- cava2/Expr.v
- cava2/ExprProperties.v
- silveroak-opentitan/hmac/hw/Hmac.v
- Sets the STATUS bit 1 to the value of `fifo_full`
- Uses CFG bit 2 (`endian_swap`) to switch input endianness
> Add HMAC registers to circuit needed by software:

- cava/Cava/Util/List.v
- cava2/TLUL.v
- firmware/IncrementWait/CavaIncrementDevice.v
- firmware/IncrementWait/Incr.v
- firmware/IncrementWait/RunIncrementWaitSoftwareOnCava.v
- firmware/RiscvMachineWithCavaDevice/InternalMMIOMachine.v
- firmware/RiscvMachineWithCavaDevice/MMIOToCava.v
- silveroak-opentitan/hmac/end2end/Bedrock2StateMachineToCavaHmac.v
- silveroak-opentitan/hmac/end2end/CavaHmacDevice.v
- silveroak-opentitan/hmac/sw/HmacSemantics.v
This PR includes @samuelgruetter's #960 (which should probably be closed without merging).
Fix the problems of `runUntilResp`, discussed in #960.
Change the IncrWait end2end proof to use the invariant-spec.
Fix TL: save the address of the outstanding request, instead of using the address from the input (which might change).
Fix TL spec.
Split the IncrWait device file to cava+spec, and end2end proof.
> Express device_implements_state_machine using only run1, without runUntilResp
